### ISSUE TITLE
Problems with poe trade macro and poe trade,please help!

### ISSUE THREAD

**Issue by akulus11** [PoE-TradeMacro/POE-TradeMacro#309] opened 2017-03-30 00:06 UTC
Everything was fine until this morning.I tried to load poe trade macro as usual(drag&drop trade macro on ahk64) and i got message ''WinHttpRequest to poe trade failed!The correct winhttp setting is:Direct acces(no proxy)''.There was option''reset proxy'' so i clicked it.It didnt help,poe trade macro still doesnt work,but what is the worst,now poe trade is slower like 10x times,it took ages to display results,also every website with like large picture(poelab for example) take very long to open.When POE is on and i try to load trade macro,game freezes and crashes.I tried many things to make it work,but nothing helps.Anyone has similiar issue?Please help!

**Comment by Eruyome** [comment] 2017-03-30 01:13
I can assure you that this change for the worse was not caused by the macro. For some reason you now have connection issues. I'm not sure about the game crashes.
Did anything change on your pc? Some software updates, new installations. Any issues with your provider? Router rebootet? 

You could also run `resources\tests\WinHttpRequest.ahk` and show me the results.

**Comment by ohlookitsben** [comment] 2017-03-30 02:01
I also get this issue. The test script seems to pass and download the file successfully. Could this be related to poe.trade itself rather than the script?

**Comment by Orinfel** [comment] 2017-03-30 08:46
I'am also getting the same problem as akulus11. Tried everything on FAQ, nothing works. After starting the script, the initializing script bar just stays there for a long time berfore an error appears "_WinHttpRequest to poe trade failed!The correct winhttp setting is:Direct acces(no proxy); your setting: Direct access(no proxy)"_. Even though sometimes it connects, but none of the hotkeys work. Ctrl+d results in it displaying "running search" for 5 min then displaying zero results. At the same time i started experiencing these problems, the poe.trade website started loading really slow, like 5 min per search slow. These problems first surfaced up after the 2.0.8 update which is probably unrelated.

**Comment by akulus11** [comment] 2017-03-30 11:06
Hi there!Today all my problems both with trademacro and poe trade are gone!I think it was poe trade related somehow.

**Comment by Eruyome** [comment] 2017-03-30 12:31
Any further confirmation that this problem is gone?

**Comment by Orinfel** [comment] 2017-03-30 14:08
Yup! Suddenly it all started working again! Thx anyway!

**Comment by Eruyome** [comment] 2017-03-30 15:13
Ok, gonna close this then, just comment if there are still issues.

**Closed by Eruyome** 2017-03-30 15:13 UTC

**Comment by Mazzariddaru** [comment] 2017-09-08 13:59
Hello, after the installation i read this message:

"Tala Moana, Exile.

 TradeMacro visits this page to make sure that it can open pages via Internet Explorer which is being used as a fallback in some circumstances. 
 For example, using Internet Explorer via ComObjects is necessary to read your user-agent in case that you need cookies for a CloudFlare bypass. 

 You should see the IE instance/window visiting this page only once so that IE can ask you for permission. 
 If this IE window opens every time at script start for you please report it. Loaded. "

I need some help, please, thanks.

**Comment by aRTy42** [comment] 2017-09-08 19:24
> Hello, after the installation i read this message:
> ...
> I need some help, please, thanks.

What do you need help with? If that message opened up only once, everything is fine. It says so in the message.
