### ISSUE TITLE
Macro works once per instance then stops functioning

### ISSUE THREAD

**Issue by KingVyrain** [PoE-TradeMacro/POE-TradeMacro#318] opened 2017-04-04 15:01 UTC
I can use any default command once (not each once total). restarting both the macro and POE allows one more use of the macro.

**Comment by Eruyome** [comment] 2017-04-04 15:05
Can you test some of the older version to see if this is an issue introduced with a specific version or maybe caused by some external factors?

**Comment by KingVyrain** [comment] 2017-04-04 15:21
I restarted my PC. .9 still did not function so I downloaded .8 and was able to do everything but ctrl+D. Then I tried .9 again and it is currently functioning fully.

**Comment by KingVyrain** [comment] 2017-04-04 15:29
(update) .9 worked for about 15 searches now the only command that works is ctrl+i/

**Comment by Eruyome** [comment] 2017-04-04 20:31
Then please test if this happens with older versions also, use the one were you are sure that it never happened to you. If you're a first time user just do some random sampling.

**Comment by KingVyrain** [comment] 2017-04-04 21:34
version .7 is currently working flawlessly. It's incredible how much I depend on this macro, thank you for all your work.

**Comment by Valerate** [comment] 2017-04-06 10:51
I just downloaded your most recent version, and I too have this issue now. Will try downgrade

**Comment by rushtothesun** [comment] 2017-04-07 20:28
Tried 2.0.9 to 2.0.5 all crash when Ctrl+D on currency. Something wrong with poe.ninja?

**Comment by OneSickBasta** [comment] 2017-04-07 20:50
@rushtothesun I have the same problems,every times i using Ctrl+D оn Ex or any other currency its crashed

**Comment by Eruyome** [comment] 2017-04-08 02:07
The currency search breaks the script, that's right, I'll try to fix that now. Could it be that this "sudden" script stopping to work always happens after using currency search, that this is the only reason?

**Comment by rushtothesun** [comment] 2017-04-08 02:44
Using anything else the script works, but Ctrl+D on currency crashes the whole thing. Ctrl+C on currency works fine, Crtl+D on anything else works fine. It's just weird that this is happening all of a sudden and even through previous versions. Seems like it would be an outside issue.

**Comment by Eruyome** [comment] 2017-04-08 03:06
All essences were added as currencies on poe.trade. The macro parses all currencies to have a list with their names and IDs to use the ids to create the search urls:
`http://currency.poe.trade/search?league=Legacy&online=x&want=6&have=4`

This parsing was broken which caused the script to freeze when using a currency search. It makes perfectly sense that these issues "suddenly" appeared, without any changes made to TradeMacro and version independent.

**Comment by InfiniteIce** [comment] 2017-04-08 13:06
Error still persists (noted 10 hours ago post and release 9 hours ago) in both new and old versions (tested newest release and 2.0.9, tested removing the folder in \my documents\ and doing a fresh install to a brand new folder.  Error persists.)

**Comment by BassMuffinFive** [comment] 2017-04-08 18:43
Same issue, Macro becomes completely unusable after ctrl+d a leaguestone. Have had the same problem three times in a row now. Now I'm here letting you know.

**Comment by Eruyome** [comment] 2017-04-09 07:13
Leaguestone and currency search issues should be fixed in version 2.0.11

**Closed** 2017-04-21 12:42 UTC
