### ISSUE TITLE
Cant run the script. Get error about additionalmacros.txt

### ISSUE THREAD

**Issue by Renen-Angel** [PoE-TradeMacro/POE-TradeMacro#454] opened 2017-08-26 00:06 UTC
1) Installed Auto Hotkey
2) Downloaded PoE trade
3) Unzipped to C:\Users\Me\Desktop\PoE Trade 
4) Double clicked Run_TradeMacro
Get error: http://i.imgur.com/wRjFlVf.png
Im on win7.

**Comment by Eruyome** [comment] 2017-08-26 03:55
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/435
The issue is discuees here (whit the solution), also please do me a favour and run the script that I posted in that thread.

**Comment by Renen-Angel** [comment] 2017-08-26 05:08
Yep. Moving it to program files 86 fixed the issue. Script ran too. Thanks! Perhaps include in the instructions that the folder should be in program files, as even somewhere else on disk C didnt work (Documents folder)

**Comment by Eruyome** [comment] 2017-08-26 13:19
I still have no idea why those files aren't copied over on script start (in some cases). Can you replace `libPoEScripts_HandleUserSettings.ahk\` with https://www.dropbox.com/s/z73t2q69vgcj7my/PoEScripts_HandleUserSettings.ahk?dl=0, remove the files from the user folder (or rename them) and run the script? Haven't done much to it, it should show a message box for every file that needs to be copied over. At least that should happen, maybe thats where the issue is.

**Comment by Renen-Angel** [comment] 2017-08-26 14:31
Now it works. I sed your file, and specifically told my antivirus to ignore autohotkey

**Comment by Eruyome** [comment] 2017-08-26 14:41
Are you saying that copying the files over with an empty user folder works now?

**Comment by Renen-Angel** [comment] 2017-08-26 15:01
I deleted the C:\Users\Me\Documents\PoE-TradeMacro folder, put your file where its supposed to go, and told my antivirus to fuck off. I suspect the last bit might have been the most important one? Maybe? It was trying to block autohotkey, though dont see why it prevented copying of some files by the script

**Comment by Eruyome** [comment] 2017-08-26 19:29
Not sure, too "paranoid"? I could copy some bad scripts there and execute them. But any software could do that...

I guess you're having a request timeout. There's a file `temp\StartupLog.txt`, it has some curl request commands and their responses. You could copy a request command to poe.trade, example:

```
"D:\Users\Eru\Documents\GitHub\POE-TradeMacro\lib\curl.exe" "http://poe.trade" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "Accept-Encoding:gzip, deflate" -H "Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "Connection:keep-alive" -H "Host:poe.trade" -H "Upgrade-Insecure-Requests:1" 
```

and paste it in a windwos cmdlet. While it's not a search it requests poe.trade, you could do it here and there and look at the output. Something like this would be expected:

```
HTTP/1.1 200 OK
Date: Sat, 26 Aug 2017 17:47:11 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=d3b40844d31825b24db977e4d065160991503769631; expires=Sun, 26-Aug-18 17:47:11 GMT; path=/; domain=.poe.trade; HttpOnly
X-Frame-Options: DENY
Content-Encoding: gzip
Server: cloudflare-nginx
CF-RAY: 39489d624562641b-FRA
```

**Comment by Renen-Angel** [comment] 2017-08-26 20:49
It seems to have trouble searching rares and such. Too many different mods it tries to plug in? As for the above instructions, I dont fully understand what you want me to do (or how to do it).

**Comment by Eruyome** [comment] 2017-08-26 22:47
<TradeMacroFolder>\temp\StartupLog.txt.
Open it, something like this:

```
Starting up PoE-TradeMacro....

----------------------------------------------------------
2017-08-26T22:28Z
----------------------------------------------------------

Requesting leagues from api.pathofexile.com...

cURL command:
"D:\Users\Eru\Documents\GitHub\POE-TradeMacro\lib\curl.exe" "http://api.pathofexile.com/leagues?type=main" -ILks -H "Host:api.pathofexile.com" -H "Connection:keep-alive" -H "Cache-Control:max-age=0" -H "Content-type:application/x-www-form-urlencoded; charset=UTF-8" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" 

Answer:
HTTP/1.1 302 Found
Server: nginx/1.8.1
Date: Sat, 26 Aug 2017 22:28:37 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=4ce5a1eda21c376fa49e89932b9fdd4f; path=/; domain=.pathofexile.com; HttpOnly
Location: /login/?redir=%2Fleagues%3Ftype%3Dmain
X-Frame-Options: SAMEORIGIN

HTTP/1.1 404
Server: nginx/1.8.1
Date: Sat, 26 Aug 2017 22:28:44 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: POESESSID=8694a7c42867353645f57cac108e40ad; path=/; domain=.pathofexile.com; HttpOnly

----------------------------------------------------------
2017-08-26T22:28Z
----------------------------------------------------------

Testing CloudFlare bypass, connecting to http://poe.trade...

cURL command:
"D:\Users\Eru\Documents\GitHub\POE-TradeMacro\lib\curl.exe" "http://poe.trade" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "Accept-Encoding:gzip, deflate" -H "Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "Connection:keep-alive" -H "Host:poe.trade" -H "Upgrade-Insecure-Requests:1" 

Answer:
HTTP/1.1 200 OK
Date: Sat, 26 Aug 2017 22:28:45 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=dbb76c46cf60f8d3c3fa3dd89412232531503786525; expires=Sun, 26-Aug-18 22:28:45 GMT; path=/; domain=.poe.trade; HttpOnly
X-Frame-Options: DENY
Content-Encoding: gzip
Server: cloudflare-nginx
CF-RAY: 394a39d6e3da6349-FRA
```

Search the section with `Testing CloudFlare bypass, connecting to http://poe.trade...`, under that line you'll find this 
```
"D:\Users\Eru\Documents\GitHub\POE-TradeMacro\lib\curl.exe" "http://api.pathofexile.com/leagues?type=main" -ILks -H "Host:api.pathofexile.com" -H "Connection:keep-alive" -H "Cache-Control:max-age=0" -H "Content-type:application/x-www-form-urlencoded; charset=UTF-8" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" 
```

Copy it, open a windows cmdlet/console window. Paste the copied string into it and execute it.

**Comment by Renen-Angel** [comment] 2017-08-26 22:59
Getting the code and pasting it into cmd.exe gives me 
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

Mine is: C:\Program Files (x86)\PoE Trade\lib\curl.exe" "http://poe.trade" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"

**Comment by Eruyome** [comment] 2017-08-27 00:55
I guess you're missing the first `"` at the beginning.

**Comment by Eruyome** [comment] 2017-08-29 20:00
Any update/progress on this issue?

**Comment by Eruyome** [comment] 2017-09-01 07:05
I'll close this until I get some feedback.

**Closed by Eruyome** 2017-09-01 07:05 UTC
