### ISSUE TITLE
I need help please, error 504

### ISSUE THREAD

**Issue by mosquito1114** [PoE-TradeMacro/POE-TradeMacro#1006] opened 2019-07-05 01:41 UTC
Hello, first of all forgive me for my English, I only speak Spanish and I'm using translators.
I get error 504 and I do not know how to fix it, could someone help me?

poeprices_log

Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Legion&i=UmFyaXR5OiBSYXJlDQpCbG9vZCBWZWlsDQpHb2xkZW4gUGxhdGUNCi0tLS0tLS0tDQpBcm1vdXI6IDgwNSAoYXVnbWVudGVkKQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA1Nw0KU3RyOiAxNTINCi0tLS0tLS0tDQpTb2NrZXRzOiBSIA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDgxDQotLS0tLS0tLQ0KKzE3IHRvIFN0cmVuZ3RoDQoxMCUgaW5jcmVhc2VkIEFybW91cg0KKzcgdG8gbWF4aW11bSBMaWZlDQorMzYlIHRvIEZpcmUgUmVzaXN0YW5jZQ0KNyUgaW5jcmVhc2VkIFN0dW4gYW5kIEJsb2NrIFJlY292ZXJ5DQozNCUgaW5jcmVhc2VkIEFybW91ciAoY3JhZnRlZCkNCisyMCB0byBtYXhpbXVtIExpZmUgKGNyYWZ0ZWQpDQo=&w=1",
        "encodedData": "UmFyaXR5OiBSYXJlDQpCbG9vZCBWZWlsDQpHb2xkZW4gUGxhdGUNCi0tLS0tLS0tDQpBcm1vdXI6IDgwNSAoYXVnbWVudGVkKQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA1Nw0KU3RyOiAxNTINCi0tLS0tLS0tDQpTb2NrZXRzOiBSIA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDgxDQotLS0tLS0tLQ0KKzE3IHRvIFN0cmVuZ3RoDQoxMCUgaW5jcmVhc2VkIEFybW91cg0KKzcgdG8gbWF4aW11bSBMaWZlDQorMzYlIHRvIEZpcmUgUmVzaXN0YW5jZQ0KNyUgaW5jcmVhc2VkIFN0dW4gYW5kIEJsb2NrIFJlY292ZXJ5DQozNCUgaW5jcmVhc2VkIEFybW91ciAoY3JhZnRlZCkNCisyMCB0byBtYXhpbXVtIExpZmUgKGNyYWZ0ZWQpDQo=",
        "encodingError": "",
        "league": "Legion",
        "requestUrl": "https://www.poeprices.info/api?l=Legion&i=UmFyaXR5OiBSYXJlDQpCbG9vZCBWZWlsDQpHb2xkZW4gUGxhdGUNCi0tLS0tLS0tDQpBcm1vdXI6IDgwNSAoYXVnbWVudGVkKQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA1Nw0KU3RyOiAxNTINCi0tLS0tLS0tDQpTb2NrZXRzOiBSIA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDgxDQotLS0tLS0tLQ0KKzE3IHRvIFN0cmVuZ3RoDQoxMCUgaW5jcmVhc2VkIEFybW91cg0KKzcgdG8gbWF4aW11bSBMaWZlDQorMzYlIHRvIEZpcmUgUmVzaXN0YW5jZQ0KNyUgaW5jcmVhc2VkIFN0dW4gYW5kIEJsb2NrIFJlY292ZXJ5DQozNCUgaW5jcmVhc2VkIEFybW91ciAoY3JhZnRlZCkNCisyMCB0byBtYXhpbXVtIExpZmUgKGNyYWZ0ZWQpDQo=",
        "retHeader": "504",
        "timeoutParam": 25
    }
}

**Comment by stanielz** [comment] 2019-07-05 01:58
I'm also having this problem on 2 different PCs out of the blue. Was working fine earlier today.

**Comment by Quiptos** [comment] 2019-07-05 02:34
Same here working this league up until today mostly error 504 sometimes I get a hit on an item once in awhile.

**Comment by MatthewWC** [comment] 2019-07-05 03:02
Also having the same issue. Tried a reinstall with no luck

**Comment by saraneth0o** [comment] 2019-07-05 03:36
Happening to me too. :(

**Comment by Mavrcks** [comment] 2019-07-05 04:58
am getting the same issue here. ctrl+d is not working. have reinstalled

**Comment by Oddwin** [comment] 2019-07-05 05:21
Same thing here.. Just lags for about 2 mins then gives an Error.

**Comment by v1clore** [comment] 2019-07-05 07:20
Same....

**Comment by KlutzyKirra** [comment] 2019-07-05 07:27
Same issue here, normal, magic items and currency and Uniques are fine for ctrl+d but all rares are coming up with errors after a long wait period of "searching".

**Comment by AngryRoleplayer** [comment] 2019-07-05 08:58
dead

**Comment by tecj** [comment] 2019-07-05 09:29
Same, only work advanced price check

**Comment by kamillasecki** [comment] 2019-07-05 10:41
same issue :
PoE trade macro request to poeprices.info returned HTTP ERROR 504

**Comment by Hella38** [comment] 2019-07-05 11:29
Hello,
Same problem here, any news ?

**Comment by saraneth0o** [comment] 2019-07-05 11:37
Apparently it wont be fixed for 2 days since the dev is away travelling and cannot reset it.

**Comment by Hella38** [comment] 2019-07-05 11:39
ok, thank you for the new ;)

**Comment by Vukovik** [comment] 2019-07-05 11:53
Same problem here, works fine with all items but rares.

**Comment by saraneth0o** [comment] 2019-07-05 11:59
It's because the rare price check pulls from a different website.

**Comment by Hella38** [comment] 2019-07-05 12:27
Don't work for card's too ;)

**Comment by mosquito1114** [comment] 2019-07-05 13:57
Does anyone know how to solve the problem? my problem is with the rare items

**Comment by jamesgmarks** [comment] 2019-07-05 14:29
This is an issue at poeprices.info which does the price predictions/guesses for un-named items. Ctrl+D will still work for unique items and some others that do not require the predictive algorithm. 

Until the site is repaired, we're just gonna have to do the work manually by ourselves. :(

**Comment by aRTy42** [comment] 2019-07-05 14:42
You can still use Ctrl+Alt+D for rares. Tick the checkboxes for the mods you think are relevant and then open it on poe.trade.

**Comment by Eruyome** [comment] 2019-07-05 21:23
The poeprices.info server is currently down and the guy behind that project is away on a trip and can't fix it for probably 2 days.

**Comment by saraneth0o** [comment] 2019-07-06 04:48
poeprices.info isn't down. I can access the site and use all its features.

**Comment by arthurmelo88** [comment] 2019-07-06 19:02
Same problem here ! error 504 

```
[06/07/2019 16:00:56] [warn] Request to poeprices.info failed.
{
    "name": "StatusCodeError",
    "statusCode": 504,
    "message": "504 - \"<html>\\r\\n<head><title>504 Gateway Time-out</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>504 Gateway Time-out</h1></center>\\r\\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\"",
    "error": "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n",
    "options": {
        "json": true,
        "uri": "https://www.poeprices.info/api?i=UmFyaXR5OiBSYXJlDQpUZW1wZXN0IEdyYXNwDQpNdXJkZXIgTWl0dHMNCi0tLS0tLS0tDQpFdmFzaW9uIFJhdGluZzogMjA3IChhdWdtZW50ZWQpDQpFbmVyZ3kgU2hpZWxkOiA0MSAoYXVnbWVudGVkKQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2Nw0KRGV4OiA1MQ0KSW50OiA1MQ0KLS0tLS0tLS0NClNvY2tldHM6IFIgRyANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA4MQ0KLS0tLS0tLS0NClNvY2tldGVkIEdlbXMgYXJlIFN1cHBvcnRlZCBieSBMZXZlbCAxNiBGYXN0ZXIgQ2FzdGluZw0KOCUgaW5jcmVhc2VkIENhc3QgU3BlZWQNCjcxJSBpbmNyZWFzZWQgRXZhc2lvbiBhbmQgRW5lcmd5IFNoaWVsZA0KKzc5IHRvIG1heGltdW0gTGlmZQ0KMTMuNyBMaWZlIFJlZ2VuZXJhdGVkIHBlciBzZWNvbmQNCisxOCUgdG8gRmlyZSBhbmQgQ29sZCBSZXNpc3RhbmNlcyAoY3JhZnRlZCkNCi0tLS0tLS0tDQpTaGFwZXIgSXRlbQ0%3D&l=Legion&s=xenontrade",
        "simple": true,
        "resolveWithFullResponse": false,
        "transform2xxOnly": false
    },
    "response": {
        "statusCode": 504,
        "body": "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n",
        "headers": {
            "server": "nginx/1.10.3 (Ubuntu)",
            "date": "Sat, 06 Jul 2019 19:00:56 GMT",
            "content-type": "text/html",
            "content-length": "192",
            "connection": "close"
        },
        "request": {
            "uri": {
                "protocol": "https:",
                "slashes": true,
                "auth": null,
                "host": "www.poeprices.info",
                "port": 443,
                "hostname": "www.poeprices.info",
                "hash": null,
                "search": "?i=UmFyaXR5OiBSYXJlDQpUZW1wZXN0IEdyYXNwDQpNdXJkZXIgTWl0dHMNCi0tLS0tLS0tDQpFdmFzaW9uIFJhdGluZzogMjA3IChhdWdtZW50ZWQpDQpFbmVyZ3kgU2hpZWxkOiA0MSAoYXVnbWVudGVkKQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2Nw0KRGV4OiA1MQ0KSW50OiA1MQ0KLS0tLS0tLS0NClNvY2tldHM6IFIgRyANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA4MQ0KLS0tLS0tLS0NClNvY2tldGVkIEdlbXMgYXJlIFN1cHBvcnRlZCBieSBMZXZlbCAxNiBGYXN0ZXIgQ2FzdGluZw0KOCUgaW5jcmVhc2VkIENhc3QgU3BlZWQNCjcxJSBpbmNyZWFzZWQgRXZhc2lvbiBhbmQgRW5lcmd5IFNoaWVsZA0KKzc5IHRvIG1heGltdW0gTGlmZQ0KMTMuNyBMaWZlIFJlZ2VuZXJhdGVkIHBlciBzZWNvbmQNCisxOCUgdG8gRmlyZSBhbmQgQ29sZCBSZXNpc3RhbmNlcyAoY3JhZnRlZCkNCi0tLS0tLS0tDQpTaGFwZXIgSXRlbQ0%3D&l=Legion&s=xenontrade",
                "query": "i=UmFyaXR5OiBSYXJlDQpUZW1wZXN0IEdyYXNwDQpNdXJkZXIgTWl0dHMNCi0tLS0tLS0tDQpFdmFzaW9uIFJhdGluZzogMjA3IChhdWdtZW50ZWQpDQpFbmVyZ3kgU2hpZWxkOiA0MSAoYXVnbWVudGVkKQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2Nw0KRGV4OiA1MQ0KSW50OiA1MQ0KLS0tLS0tLS0NClNvY2tldHM6IFIgRyANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA4MQ0KLS0tLS0tLS0NClNvY2tldGVkIEdlbXMgYXJlIFN1cHBvcnRlZCBieSBMZXZlbCAxNiBGYXN0ZXIgQ2FzdGluZw0KOCUgaW5jcmVhc2VkIENhc3QgU3BlZWQNCjcxJSBpbmNyZWFzZWQgRXZhc2lvbiBhbmQgRW5lcmd5IFNoaWVsZA0KKzc5IHRvIG1heGltdW0gTGlmZQ0KMTMuNyBMaWZlIFJlZ2VuZXJhdGVkIHBlciBzZWNvbmQNCisxOCUgdG8gRmlyZSBhbmQgQ29sZCBSZXNpc3RhbmNlcyAoY3JhZnRlZCkNCi0tLS0tLS0tDQpTaGFwZXIgSXRlbQ0%3D&l=Legion&s=xenontrade",
                "pathname": "/api",
                "path": "/api?i=UmFyaXR5OiBSYXJlDQpUZW1wZXN0IEdyYXNwDQpNdXJkZXIgTWl0dHMNCi0tLS0tLS0tDQpFdmFzaW9uIFJhdGluZzogMjA3IChhdWdtZW50ZWQpDQpFbmVyZ3kgU2hpZWxkOiA0MSAoYXVnbWVudGVkKQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2Nw0KRGV4OiA1MQ0KSW50OiA1MQ0KLS0tLS0tLS0NClNvY2tldHM6IFIgRyANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA4MQ0KLS0tLS0tLS0NClNvY2tldGVkIEdlbXMgYXJlIFN1cHBvcnRlZCBieSBMZXZlbCAxNiBGYXN0ZXIgQ2FzdGluZw0KOCUgaW5jcmVhc2VkIENhc3QgU3BlZWQNCjcxJSBpbmNyZWFzZWQgRXZhc2lvbiBhbmQgRW5lcmd5IFNoaWVsZA0KKzc5IHRvIG1heGltdW0gTGlmZQ0KMTMuNyBMaWZlIFJlZ2VuZXJhdGVkIHBlciBzZWNvbmQNCisxOCUgdG8gRmlyZSBhbmQgQ29sZCBSZXNpc3RhbmNlcyAoY3JhZnRlZCkNCi0tLS0tLS0tDQpTaGFwZXIgSXRlbQ0%3D&l=Legion&s=xenontrade",
                "href": "https://www.poeprices.info/api?i=UmFyaXR5OiBSYXJlDQpUZW1wZXN0IEdyYXNwDQpNdXJkZXIgTWl0dHMNCi0tLS0tLS0tDQpFdmFzaW9uIFJhdGluZzogMjA3IChhdWdtZW50ZWQpDQpFbmVyZ3kgU2hpZWxkOiA0MSAoYXVnbWVudGVkKQ0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA2Nw0KRGV4OiA1MQ0KSW50OiA1MQ0KLS0tLS0tLS0NClNvY2tldHM6IFIgRyANCi0tLS0tLS0tDQpJdGVtIExldmVsOiA4MQ0KLS0tLS0tLS0NClNvY2tldGVkIEdlbXMgYXJlIFN1cHBvcnRlZCBieSBMZXZlbCAxNiBGYXN0ZXIgQ2FzdGluZw0KOCUgaW5jcmVhc2VkIENhc3QgU3BlZWQNCjcxJSBpbmNyZWFzZWQgRXZhc2lvbiBhbmQgRW5lcmd5IFNoaWVsZA0KKzc5IHRvIG1heGltdW0gTGlmZQ0KMTMuNyBMaWZlIFJlZ2VuZXJhdGVkIHBlciBzZWNvbmQNCisxOCUgdG8gRmlyZSBhbmQgQ29sZCBSZXNpc3RhbmNlcyAoY3JhZnRlZCkNCi0tLS0tLS0tDQpTaGFwZXIgSXRlbQ0%3D&l=Legion&s=xenontrade"
            },
            "method": "GET",
            "headers": {
                "accept": "application/json"
            }
        }
    }
}

```

**Comment by Kammerjunk** [comment] 2019-07-07 03:44
@saraneth0o is right, the server isn't down - although it's slow to respond, the site itself works and I've used it manually for the past couple of days. I also tried requesting the server through the href @arthurmelo88 posted and got a response:
```
{"min": 7.2, "max": 10.799999999999999, "currency": "chaos", "warning_msg": "", "error": 0, "pred_explanation": [["(pseudo) (total) +# to maximum Life", 0.6779896954530031], ["Socketed Gems are Supported by Level # Faster Casting", 0.11636879857355516], ["# Life Regenerated per second", 0.06214063447997451], ["ER", 0.05125838535899744], ["#% increased Evasion and Energy Shield", 0.020908724493634494], ["ES", 0.015325764562979868], ["(pseudo) (total) +#% to Cold Resistance", 0.00797700636769499], ["(pseudo) (total) #% increased Cast Speed", -0.048030990710160405]], "pred_confidence_score": 68.93035648036091, "error_msg": ""}
```
504 is a gateway timeout. I can't reproduce the error currently (though I've been having it for the past couple of days), but if it keeps happening for you, you could try increasing the timeout in `%USERPROFILE%\Documents\PoE-TradeMacro\config_trade.ini`

**Closed** 2019-12-08 19:12 UTC
