### ISSUE TITLE
2.10.2 "parsing the currency data (json) from poe.ninja failed"

### ISSUE THREAD

**Issue by dsnvwlmnt** [PoE-TradeMacro/POE-TradeMacro#729] opened 2018-06-02 16:03 UTC
2.10.2 is not fully working for me.

Windows 10, ahk 1.1.28.02

![image](https://user-images.githubusercontent.com/14173022/40878289-a588e7ba-6643-11e8-852d-2f742205b309.png)

**Comment by Eruyome** [comment] 2018-06-03 07:20
Is this persistent? What league do yuo have slected in the settings? What value is assigned to the key `searchLeague` in `%useprofile%\documents\po-etrademacr\config_trade_ini`?

**Comment by dsnvwlmnt** [comment] 2018-06-03 15:34
I persistently got that error every time i lauunched the macro from right before Incursion, at Incursion Queue, after the start, and for the first 24 hours. It didn't prevent anything from workig once i Ctrl+L'd into the right league though.

Today, i didn't get the error message.

**Comment by slasso93** [comment] 2018-06-03 18:26
If I change the league search to "incursion" it gives the parse error. "tmpstandard" does not

**Comment by Eruyome** [comment] 2018-06-04 05:29
@dsnvwlmnt So this is solved for you?
@slasso93 You mean manually writing the ini key to "incursion" fails but setting "tmpstandard" in the menu works?
@cestarix are you actually using "tmpstandard/tmphardcore" in the settings?

**Comment by dsnvwlmnt** [comment] 2018-06-04 05:51
Everything seems fine for me at the moment.

**Comment by slasso93** [comment] 2018-06-04 06:21
@Eruyome Idk what happened. But i was having issues where the league would change to standard when i did a price search on an item. Even when I kept trying to set tmpstandard. I also had "incursion" in the drop down. When I closed and reopened poe trademacro, it would not start correctly. I deleted the trade macro folder and redownloaded the latest release. Still same issue (because the ini file is in a different location). I changed the league manually back to tmpstandard in the ini file and now it works. There's no incursion in the drop down so I'm confused how it let me do it.

**Comment by Eruyome** [comment] 2018-06-04 13:14
"incursion" should never be written to the ini nor be visible in the settings menu. If you have any idea on how to reproduce this please tell me. Could it be that you run the macro in the time where Incursion was supported on poe.trade but the league wasn't live yet?
The macro tries to match poe.trades leagues to the ones from GGGs API but also schows the ones that are only supported on poe.trade, which may not be needed anymore but was at some point for 1month races. Mayb that caused the macro to write incursion to the  ini and the macro couldn't figure out how to handle it.

**Comment by Suddow** [comment] 2018-06-04 15:13
I have the same issue and Incursion is not written in the file.

**Comment by ndimario** [comment] 2018-06-07 03:34
I've had this issue for some time (still have it). I tried deleting the folder and appdata with trade macro in it. redownloaded and reran everything. Same issue.

**Comment by tamaroth** [comment] 2018-06-07 18:19
I had the same issue. I have checked the file:

`%userprofile%\Documents\PoE-TradeMacro\config_trade.ini` 

and indeed I have had:

`searchLeague=incursion`

After changing it to 

`searchLeague=tmpstandard` and restaring PoE-TradeMacro, everything is working fine.

As you have mentioned, I have used poe-tm when league was on on poe.trade but wasn't active just yet, maybe that's why.

Other than that I have no idea how and when that value was changed.

**Comment by v1nt06** [comment] 2018-06-09 07:09
I have the same issue on 2.10.4. I got this error yesterday. I did a clean install (%userprfile%\Documents\PoE-TradeMacro was deleted) but an error message is still showing.
League (by default and not changed after installation):
`searchLeague=tmpstandard`

**Comment by Eruyome** [comment] 2018-06-10 09:36
What happens if you run the macro, and change the league, either via hotkey or via menu? Do you also get an error message?

**Comment by v1nt06** [comment] 2018-06-10 10:14
After changing league via Ctrl+L error message disappears for a while (without reloading macro).

**Comment by Eruyome** [comment] 2018-06-10 12:04
For a while? So it can reappear while leaving the macro running? And changing the league doesn't cause an error, only the first macro start?

The macro makes the same request to poe.ninja on startup, on changing leagues and periodically in the background to update the data.

**Comment by v1nt06** [comment] 2018-06-10 14:14
Sometimes I have that issue when starting the macro or that appears after some time when the macro was launched before and. But after changing league via Ctrl+L that error disappears. BTW, an error window appears 3 or 4 times. Then, after some time this situation repeated and I change league again to remedy the situation.

PS: I did't use any VPN or Proxy services and I can open poe.ninja in browser.

**Comment by Eruyome** [comment] 2018-06-12 09:42
So basically the request works in general.
For some reason there are times where it doesn't, which would suggest that this issue is either on your end or that there are occasions where the issue lies between your pc/router to poe.ninja.

I'll try and make a dev version that can show some more information, but I don't know whether this can show anything relevant.

**Comment by v1nt06** [comment] 2018-06-12 13:10
An error appears 5 times (1 time per league including event leagues).

**Comment by Eruyome** [comment] 2018-06-15 11:54
We can take a look at the response that you get from poe.ninja.

This is the curl request, here for the hc incursion league:
```
"D:\Users\Eru\Documents\GitHub\POE-TradeMacro\lib\curl.exe" "http://poe.ninja/api/Data/GetCurrencyOverview?league=tmphardcore" -ILks --max-time 30
```

It uses my local path to trademacros curl.exe, you can easily see yours by opening `temp\StartUpLog.exe` where some similiar requests are displayed, but with your local paths.

Take the command above and replace the path to `curl.exe` with a valid one on your system. Then open a windows console/terminal/cmd window and execute this command there.

You'll get some output like this:
![image](https://user-images.githubusercontent.com/16058242/41466674-8e9b4f9c-70a3-11e8-970d-6c059de03652.png)

At least you should if everything works, but I guess it doesn't at least sometimes in your case.

**Comment by Eruyome** [comment] 2018-06-15 12:57
I've made it easier and added one request to poe.ninja to the StartUpLog.txt in this dev version https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/dev.zip

**Comment by v1nt06** [comment] 2018-06-20 14:35
No errors after few days on dev version.

**Comment by Eruyome** [comment] 2018-06-20 17:39
Good to hear, I'll keep the issue open for a bit longer for visibilty and in case the issue still reappears.

**Comment by Simpsonboy77** [comment] 2018-09-13 06:47
I get the same issue. I reinstalled the trade macro and deleted %userprofile%\Documents\PoE-TradeMacro\.

When I do E:\Data\POE\POE-TradeMacro\lib>curl "http://poe.ninja/api/Data/GetCurrencyOverview?league=tmphardcore" -ILks --max-time 30

I get a 301 moved permanently response. When I open it in the browser it loads the JSON properly.

I don't have curl anywhere else on my system, or in my PATH. When I go to C:\ and run curl it says not found. So it should definitely be using TradeMacro's curl.

In StartupLog.txt I only see 3x 200 responses.

**Comment by cryzed** [comment] 2019-01-04 23:20
Fair warning: I'm running this via wine on Linux, but I always get the same issue without fail when starting the script; the rest seems to work perfectly.

**Comment by Eruyome** [comment] 2019-01-07 20:08
Can you make sure that all files in `<tm folder>\temp` are deleted properly before starting the script? Not sure if related but I had at least one user where this failed. Downloaded json will be appended to the corresponding file (after deleting it first, which failed).

This was related to GGGs API data for leagues though but it's the same principle. The file contained the same contents multiple times which broke the json structure and therefore the json parsing.

Are you sure that's the entire startuplog? It seems quite short, completely missing  this:

```
----------------------------------------------------------
2019-01-07T19:52Z
----------------------------------------------------------

Requesting currency data from poe.ninja...

cURL command:
"D:\Users\Eruyome\Documents\GitHub\POE-TradeMacro\lib\curl.exe" "https://poe.ninja/api/Data/GetCurrencyOverview?league=Betrayal" -ILks --max-time 20 

Answer: HTTP/2 200 
date: Mon, 07 Jan 2019 19:52:30 GMT
content-type: application/json; charset=utf-8
set-cookie: __cfduid=d0e1de45d2d0e7dc134dbd3575ef379ee1546890750; expires=Tue, 07-Jan-20 19:52:30 GMT; path=/; domain=.poe.ninja; HttpOnly; Secure
vary: Accept-Encoding
cache-control: public, max-age=900
expires: Mon, 07 Jan 2019 19:56:55 GMT
cf-cache-status: HIT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 4958f717abb9befd-FRA
```

**Closed** 2019-01-11 22:38 UTC

**Comment by cryzed** [comment] 2019-01-12 12:09
Sorry for the late reply, just saw this -- but I see that you were a bit quick on the draw (unless you found the source of the issue?). I reinstalled the script several times (including clearing out all temp data/directories created by the script), and I am positive those were the full contents of the file.

If you want me to rerun the script with a completely fresh state and then upload the logs again, I will definitely do so.

**Comment by cryzed** [comment] 2019-01-12 20:57
Just creating a new comment so you get notified; I don't think edits trigger a new notification.

**Comment by Eruyome** [comment] 2019-01-12 21:15
I am manually parsing the status code from the response and I made some improvements but this is not really relevant here since that error gets displayed if parsing the downloaded JSON data from these currency files here fails:

![image](https://user-images.githubusercontent.com/16058242/51078576-72a8c480-16b7-11e9-9f4e-fdc4c31d9d2f.png)

At least if parsing the one from the currently selected league fails. How do those files look in your case? Do the exist? Do they containt valid JSON?

**Comment by cryzed** [comment] 2019-01-12 21:34
Wow, the dev version actually worked. You must have recently changed something that fixed the issue. I did not get the error message, and the files exists and are valid JSON: https://i.imgur.com/po0Z6PA.png. Here's the new StartupLog.txt: https://gist.github.com/cryzed/7f450cee6776b08c7fc49181a1da4394.

**Comment by Eruyome** [comment] 2019-01-12 21:41
You're welcome.
