### ISSUE TITLE
Error when valueing rare items

### ISSUE THREAD

**Issue by jealousmuch** [PoE-TradeMacro/POE-TradeMacro#857] opened 2018-12-27 08:14 UTC
Hello! Today an error occured when checking rare items for their value. Checked poeprices log and the last parse was "failed": "ERROR: Parsing response failed, empty response! ".
I just wanted to use it to value the stats on the rare item, never had the problem before even if a similar item wasnt on the market. Still can check the uniques for prices.

Here's the full poeprices_log file in case its needed: https://pastebin.com/MGucVWuu

AHK version: v1.1.30.01
Windows version: 10

**Comment by OmniLight16** [comment] 2018-12-27 08:52
Same issue please help.

heres my poeprices_log file in case its needed: https://pastebin.com/cwe5crXH

**Comment by onuraydin** [comment] 2018-12-27 09:31
+1

**Comment by Eruyome** [comment] 2018-12-28 14:44
And both urls from the log file work in your browser?

**Comment by jealousmuch** [comment] 2018-12-28 16:07
? i can open the pastebin doc and view it

just started poe and played, today it seems to work again, no clue why it didnt yesterday

**Comment by Eruyome** [comment] 2018-12-29 12:31
Huh ok that sounds good. Anyway, what I meant is this:

```
{
"added": {
"browserUrl": "https://www.poeprices.info/api?l=Betrayal&i=UmFyaXR5OiBSYXJlDQpDaGltZXJpYyBHeXJlDQpUd28tU3RvbmUgUmluZw0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA0OA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDcwDQotLS0tLS0tLQ0KKzEyJSB0byBDb2xkIGFuZCBMaWdodG5pbmcgUmVzaXN0YW5jZXMNCi0tLS0tLS0tDQpBZGRzIDMgdG8gNSBQaHlzaWNhbCBEYW1hZ2UgdG8gQXR0YWNrcw0KMjAlIGluY3JlYXNlZCBSYXJpdHkgb2YgSXRlbXMgZm91bmQNCisxNSUgdG8gYWxsIEVsZW1lbnRhbCBSZXNpc3RhbmNlcw0KKzI2JSB0byBMaWdodG5pbmcgUmVzaXN0YW5jZQ0KMTklIGluY3JlYXNlZCBFbGVtZW50YWwgRGFtYWdlIHdpdGggQXR0YWNrIFNraWxscw0KKzUyIHRvIG1heGltdW0gTGlmZQ0K&w=1",
"encodedData": "UmFyaXR5OiBSYXJlDQpDaGltZXJpYyBHeXJlDQpUd28tU3RvbmUgUmluZw0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA0OA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDcwDQotLS0tLS0tLQ0KKzEyJSB0byBDb2xkIGFuZCBMaWdodG5pbmcgUmVzaXN0YW5jZXMNCi0tLS0tLS0tDQpBZGRzIDMgdG8gNSBQaHlzaWNhbCBEYW1hZ2UgdG8gQXR0YWNrcw0KMjAlIGluY3JlYXNlZCBSYXJpdHkgb2YgSXRlbXMgZm91bmQNCisxNSUgdG8gYWxsIEVsZW1lbnRhbCBSZXNpc3RhbmNlcw0KKzI2JSB0byBMaWdodG5pbmcgUmVzaXN0YW5jZQ0KMTklIGluY3JlYXNlZCBFbGVtZW50YWwgRGFtYWdlIHdpdGggQXR0YWNrIFNraWxscw0KKzUyIHRvIG1heGltdW0gTGlmZQ0K",
"encodingError": "",
"league": "Betrayal",
"requestUrl": "https://www.poeprices.info/api?l=Betrayal&i=UmFyaXR5OiBSYXJlDQpDaGltZXJpYyBHeXJlDQpUd28tU3RvbmUgUmluZw0KLS0tLS0tLS0NClJlcXVpcmVtZW50czoNCkxldmVsOiA0OA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDcwDQotLS0tLS0tLQ0KKzEyJSB0byBDb2xkIGFuZCBMaWdodG5pbmcgUmVzaXN0YW5jZXMNCi0tLS0tLS0tDQpBZGRzIDMgdG8gNSBQaHlzaWNhbCBEYW1hZ2UgdG8gQXR0YWNrcw0KMjAlIGluY3JlYXNlZCBSYXJpdHkgb2YgSXRlbXMgZm91bmQNCisxNSUgdG8gYWxsIEVsZW1lbnRhbCBSZXNpc3RhbmNlcw0KKzI2JSB0byBMaWdodG5pbmcgUmVzaXN0YW5jZQ0KMTklIGluY3JlYXNlZCBFbGVtZW50YWwgRGFtYWdlIHdpdGggQXR0YWNrIFNraWxscw0KKzUyIHRvIG1heGltdW0gTGlmZQ0K"
},
"failed": "ERROR: Parsing response failed, empty response! "
}
```

The fields/keys `browserUrl`and `requestUrl` have an url as a value that you can open in your browser.

**Comment by Eruyome** [comment] 2019-01-11 22:13
Issues should be fixed, was mainly caused by their server issues.

**Closed by Eruyome** 2019-01-11 22:13 UTC
