### ISSUE TITLE
Ludicrous price estimation

### ISSUE THREAD

**Issue by SonOfDiablo** [PoE-TradeMacro/POE-TradeMacro#107] opened 2016-12-04 14:41 UTC
So I just started in the Breach league and got a few uniques.
I wanted to see if they were worth anything and got this:
![image](https://farm6.staticflickr.com/5679/31268333982_dcd9a6a462_o.png)

Something seems off on both of these estimations :/

I would love to get this fixed as fast as possible :)

**Comment by McHearty** [comment] 2016-12-04 22:48
I too am having this issue

**Comment by Eruyome** [comment] 2016-12-04 23:09
The script is actually working as intended. While scraping poe.trade it reads the chaos equivalent from here:
![error](https://cloud.githubusercontent.com/assets/16058242/20869950/66860790-ba7e-11e6-8ada-a5bf08c9af07.png)

`data-value`  has the value we want and before this value was correct. Now it isn't. So there are 2 solutions:
1. Wait until it's fixed on poe.trade but I have no idea how long this could take.
2. Use the actual displayed value, determine the currency and find out try to use some median of the currency trades to get ratios and calculate the chaos equivalent with that.

**Comment by Dillybob92** [comment] 2016-12-05 08:04
Fucking retards

**Comment by Eruyome** [comment] 2016-12-05 13:15
I've added a workaround, hope that works without problems. Reopen this if there seems to be anything wrong.

**Closed by Eruyome** 2016-12-05 13:15 UTC
