### ISSUE TITLE
"League is not active private league are not supported now"

### ISSUE THREAD

**Issue by dragoncatTest** [PoE-TradeMacro/POE-TradeMacro#1023] opened 2019-09-07 11:51 UTC
When I press "Ctrl+D" to search rare items, it will return "league is not active private league are not supported now". But I am so sure my "league" in options is “tmpstandard”. It just cant work on rare Items, still useful in other items. Dont have any idea to fix it.
AHK version:AutoHotkey_1.1.26.01
Windows version:Win10 1903 64bit

**Comment by Seriousedy** [comment] 2019-09-07 12:09
Yeah I got the exact same problem too. Standard and HC Standard work fine, no problem there, but as soon as I switch to blight hc or not, it just gives the error. I uninstalled, reinstalled, rebooted whatever you could think of, I still can't figure out what the problem is. It recognises that I'm in Blight league if I use poe.trade, but as soon as I make a request to poeprices.info it just spits this error at me. I made sure that poeprices.info is working and it left me with a sour taste in my mouth.

**Comment by AnimeJ41081** [comment] 2019-09-07 13:39
I'm also having this issue. Super frustrating.

**Comment by shokilicious** [comment] 2019-09-07 13:43
Me and 2 friends aswell. 
Only affects rare item search.

**Comment by Eruyome** [comment] 2019-09-07 13:57
This seems to be an issue with poeprices,info, I have already wrote them about it

**Comment by bolivir** [comment] 2019-09-07 16:51
On my side i noticed it was my virus scanner (avast) that was causing this problem.

**Comment by AnimeJ41081** [comment] 2019-09-08 04:05
The error message I was seeing in 2.15.1 was specific to poe.trade. It's been resolved with 2.15.2.

**Closed** 2019-09-13 15:02 UTC
