### ISSUE TITLE
Custom Macros Bugged

### ISSUE THREAD

**Issue by mannerpots** [PoE-TradeMacro/POE-TradeMacro#393] opened 2017-07-21 17:14 UTC
I wrote an incorrect macro in the custom macros folder which caused the script to crash. However, after deleting the file and rerunning the script, it still crashes and references the custom macro.

**Comment by Eruyome** [comment] 2017-07-22 10:22
That should only happen if the file isn't really deleted or if you didn't use `Run_TradeMacro.ahk` to start the macro but `_TradeMacroMain.ahk` instead. Can you confirm whether this is/was the case?

**Comment by LepuavkoDV** [comment] 2017-07-22 18:03
seems like is also backed up in c:\Users\%USERNAME%\Documents\PoE-TradeMacro
And even after you remove them from installation folder, app keep loading things from here.

**Comment by mannerpots** [comment] 2017-07-22 18:12
@Eruyome I deleted the file and emptied recycle bin, and I was using `Run_TradeMacro.ahk`. I'm guessing it was backed up somewhere like LepuavkoDV mentioned. This seems like a bug, I would expect that deleting a custom file would remove it from the script

**Comment by Eruyome** [comment] 2017-07-23 12:02
Alright, I'll take a look at this.

**Comment by Eruyome** [comment] 2017-07-24 11:12
I can't reproduce this at all. I create a `test.ahk` with some hotkey in `\Users\%USERNAME%\Documents\PoE-TradeMacro\CustomMacros`, start `Run_TradeMacro.ahk` and my hotkey works. Then I delete that file and it doesn't work anymore when running `Run_TradeMacro.ahk`.

`Run_TradeMacro.ahk` has a function `AppendCustomMacros()`, replace it with this:

```
AppendCustomMacros(userDirectory)
{
	If(!InStr(FileExist(userDirectory "\CustomMacros"), "D")) {
		FileCreateDir, %userDirectory%\CustomMacros\
	}
	
	appendedMacros := "`n`n"
	extensions := "txt,ahk"
	
	SplashTextOff
	Loop %userDirectory%\CustomMacros\*
	{
		If A_LoopFileExt in %extensions% 
		{
			FileRead, tmp, %A_LoopFileFullPath%
			FileGetAttrib, AttributeString,  %A_LoopFileName%
			MsgBox % "Appended macro file: " A_LoopFileName "`n" "File attribute string: " AttributeString			
			appendedMacros .= "; appended custom macro file: " A_LoopFileName " ---------------------------------------------------"
			appendedMacros .= "`n" tmp "`n`n"
		}
	}
	StartSplashScreen()
	
	Return appendedMacros
}

It shows every appended file with name and file attribute string (https://autohotkey.com/docs/commands/FileGetAttrib.htm)
```

**Comment by mannerpots** [comment] 2017-07-24 14:23
I think the bug was cause because the hotkey I wrote had an error and it
was crashing the script before it checked the custom folder. Try it again
with a broken macro? Specifically i
The error was invalid hotkey.

**Comment by Eruyome** [comment] 2017-07-24 17:30
Every script start rebuilds the main script by deleting it, recreating it and appending all other scripts to it. The macros from CutomMacros are only appended while checking that folder. You said that you deleted your custom macro, so it shouldn't be appendend in any way to the newly created main file. Whether a script is invalid can't be known at this point, only after executing this main script after everything is appended. Therefore an invalid script can't crash this whole process of combining/merging scripts.

**Comment by mannerpots** [comment] 2017-07-24 17:51
Ok, well I will try to recreate the issue tonight (I solved it by
reinstalling the script) and get back to you with details if I can.

**Comment by Eruyome** [comment] 2017-08-02 08:22
WIll close this for now.

**Closed by Eruyome** 2017-08-02 08:22 UTC
