### ISSUE TITLE
Minimise issues

### ISSUE THREAD

**Issue by Morbeus1** [PoE-TradeMacro/POE-TradeMacro#655] opened 2018-01-21 16:55 UTC
Hello , i been using this for 2 days and i got issues since day one. So when i stop play path of exile i turn off the macro too and everything else minimises constantly. I try to play hots and it minimise the game all the time only pc reboot fixes this. Any suggestions?

**Comment by Eruyome** [comment] 2018-01-22 09:30
If the macro is turned off/exited it won't do anything. No chance. Therefore your issue can't be related to TradeMacro itself.

**Comment by Morbeus1** [comment] 2018-01-22 18:40
Well i dont know then when i restart everyting is ok no minimise issues even after playing poe and then exit. The only thing i can come up is something stays turned on  but i checked the task manager there was nothing i dont recognise. Maybe the macro is having isues with other games that are fullscreened. I donwloaded the macro from the code page here and followed the guide, unrared the macro and ran the file. I have no idea what can cause this issue. AHK is just script making program so that cant be it. The other thing i  think of is the macro itself making some issues with something else on the Pc but no way to find wich exactly. Also i dont see Curl.exe in the task manager when macro is running

**Comment by Eruyome** [comment] 2018-01-23 05:19
Curl is not running constantly, it get's used via commandline when making http requests.

I see absolutely no way for AHK, specifically TradeMacro to influence your PC in any way when it's closed/not running. The macro also doesn't change anything on your pc, so running the macro can't change your PCs behaviour after closing the macro. Are you really sure that this only happens after running TM? Have you done the same (playing PoE, starting/using other software tha you normally use) but everything works as intended? Then running TM fucks everything up?

**Comment by Morbeus1** [comment] 2018-01-23 09:37
I just tested, i started HOTS withot macro i sset it to windowed fullscreen then i exit, started the macro  and ran HOTS- no issues. Then i revert HOTS to fullscreen then run macro again and the minimize spam began. So its making some conflict with fullscreen .exes but macro is stopped how it could make conflicts???

**Comment by Morbeus1** [comment] 2018-01-23 17:09
yep i can confirm- Macro turned off( closed) every game that has fullscreen mode on minimizes (even POE). When i  change to fullscreen( windowed) the minimize issue stops

**Comment by Eruyome** [comment] 2018-02-28 10:48
Sorry for not answering for a while. Still don't really know what could be the issue here. @aRTy42 any idea?

**Comment by aRTy42** [comment] 2018-02-28 11:15
Is it minimizing all fullscreen windows **once** when you close the script, or do you have ongoing issues even while the script should be terminated? The initial reports and the last report read quite differently. I have no idea how the script could cause ongoing effects after you've exited it. Running multiple things in fullscreen on the other hand can have odd effects (PoE in particular refuses to minimize without a special command for example), so issues with that while the script is running sound quite possible.

**Closed** 2018-03-17 04:19 UTC
