### ISSUE TITLE
Target label does not exist. Specifically: AM_AssignHotkeys

### ISSUE THREAD

**Issue by Fone-Bone** [PoE-TradeMacro/POE-TradeMacro#415] opened 2017-08-09 01:41 UTC
Hi

I get the following message when I start poe-trademacro. It has come after an update.

Have tried the various suggestions from this forum and from FAQ but nothing helps.

<img width="339" alt="udklip" src="https://user-images.githubusercontent.com/30850087/29101720-835ea018-7cb4-11e7-89a0-151c0fdeae4a.PNG">

**Comment by Eruyome** [comment] 2017-08-09 10:55
So you deleted `AdditionalMacros.txt` from `C:\Users\<YourUserHere>\Documents\PoE-TradeMacro\`, restarted the script via `Run_TradeMacro.ahk` and it still doesn't work?

**Comment by Fone-Bone** [comment] 2017-08-09 11:18
Hi Eruyome

Yes eksaktly.

I can use version 2.3.4 again as long as it runs from folder downloads.

**Comment by Eruyome** [comment] 2017-08-09 11:46
AdditionalMacros gets merged into ItemInfo/TradeMacro. This new script then gets started, your issue is caused by TradeMacro expecting the new AdditionalMacros, while it seems to have the old one from 2.3.4.

Can you upload your (invisible) _TradeMacroMain.ahk from the TradeMacro folder root somewhere so that I can take a look at it?

**Comment by Fone-Bone** [comment] 2017-08-09 12:32
Hi Eruyome
Thanks for your help. I really appreciate it.

I have copied the version 3.0 script Run_TradeMacro.ahk. I hope that's what you're looking for, because I do not quite understand what you mean by (invisible) _TradeMacro.ahk.

; #####################################################################################################################
; # This script merges TradeMacro, TradeMacroInit, PoE-ItemInfo and AdditionalMacros into one script and executes it.
; # We also have to set some global variables and pass them to the ItemInfo/TradeMacroInit scripts. 
; # This is to support using ItemInfo as dependancy for TradeMacro.
; #####################################################################################################################
#Include, %A_ScriptDir%\resources\VersionTrade.txt

TradeMsgWrongAHKVersion := "AutoHotkey v" . TradeAHKVersionRequired . " or later is needed to run this script. `n`nYou are using AutoHotkey v" . A_AhkVersion . " (installed at: " . A_AhkPath . ")`n`nPlease go to http://ahkscript.org to download the most recent version."
If (A_AhkVersion < TradeAHKVersionRequired)
{
    MsgBox, 16, Wrong AutoHotkey Version, % TradeMsgWrongAHKVersion
    ExitApp
}

arguments := ""
Loop, %0%  ; For each parameter
{
	arguments .= " " Trim(%A_Index%)
}

If (!InStr(arguments, "-noelevation", 0)) {
	RunAsAdmin(arguments)
}
If (InStr(arguments, "-nosplash", 0)) {
	skipSplash := 1	
} Else {
	skipSplash := 0
	StartSplashScreen()
}

If (!PoEScripts_CreateTempFolder(A_ScriptDir, "PoE-TradeMacro")) {
	ExitApp
}

/*	 
	Set ProjectName to create user settings folder in A_MyDocuments
*/
projectName			:= "PoE-TradeMacro"
FilesToCopyToUserFolder	:= ["\resources\config\default_config_trade.ini", "\resources\config\default_config.ini", "\resources\ahk\default_AdditionalMacros.txt", "\resources\ahk\default_MapModWarnings.txt"]
overwrittenFiles 		:= PoEScripts_HandleUserSettings(projectName, A_MyDocuments, projectName, FilesToCopyToUserFolder, A_ScriptDir)
isDevelopmentVersion	:= PoEScripts_isDevelopmentVersion()
userDirectory			:= A_MyDocuments . "\" . projectName . isDevelopmentVersion

PoEScripts_CompareUserFolderWithScriptFolder(userDirectory, A_ScriptDir, projectName)

/*	 
	merge all scripts into `_TradeMacroMain.ahk` and execute it.
*/
FileRead, info		, %A_ScriptDir%\resources\ahk\POE-ItemInfo.ahk
FileRead, tradeInit	, %A_ScriptDir%\resources\ahk\TradeMacroInit.ahk
FileRead, trade	, %A_ScriptDir%\resources\ahk\TradeMacro.ahk
FileRead, addMacros	, %userDirectory%\AdditionalMacros.txt

info		:= "`n`r`n`r" . info . "`n`r`n`r"
addMacros	:= "#IfWinActive Path of Exile ahk_class POEWindowClass ahk_group PoEexe" . "`n`r`n`r" . addMacros . "`n`r`n`r"
addMacros	.= AppendCustomMacros(userDirectory)

CloseScript("_TradeMacroMain.ahk")
CloseScript("_ItemInfoMain.ahk")
FileDelete, %A_ScriptDir%\_TradeMacroMain.ahk
FileDelete, %A_ScriptDir%\_ItemInfoMain.ahk
FileCopy,   %A_ScriptDir%\resources\ahk\TradeMacroInit.ahk, %A_ScriptDir%\_TradeMacroMain.ahk

FileAppend, %info%		, %A_ScriptDir%\_TradeMacroMain.ahk
FileAppend, %addMacros%	, %A_ScriptDir%\_TradeMacroMain.ahk
FileAppend, %trade%		, %A_ScriptDir%\_TradeMacroMain.ahk

; set script hidden
FileSetAttrib, +H, %A_ScriptDir%\_TradeMacroMain.ahk
; pass some parameters to TradeMacroInit
Run "%A_AhkPath%" "%A_ScriptDir%\_TradeMacroMain.ahk" "%projectName%" "%userDirectory%" "%isDevelopmentVersion%" "%overwrittenFiles%" "isMergedScript" "%skipSplash%"

ExitApp


; ####################################################################################################################
; # functions
; ####################################################################################################################

CloseScript(Name)
{
	DetectHiddenWindows On
	SetTitleMatchMode RegEx
	IfWinExist, i)%Name%.* ahk_class AutoHotkey
		{
		WinClose
		WinWaitClose, i)%Name%.* ahk_class AutoHotkey, , 2
		If ErrorLevel
			Return "Unable to close " . Name
		Else
			Return "Closed " . Name
		}
	Else
		Return Name . " not found"
}

RunAsAdmin(arguments) 
{
    ShellExecute := A_IsUnicode ? "shell32\ShellExecute":"shell32\ShellExecuteA"
    If Not A_IsAdmin 
    { 
		If A_IsCompiled 
			DllCall(ShellExecute, uint, 0, str, "RunAs", str, A_ScriptFullPath . " " . arguments, str, A_WorkingDir, int, 1) 
		Else 
			DllCall(ShellExecute, uint, 0, str, "RunAs", str, A_AhkPath, str, """" . A_ScriptFullPath . """" . " " . arguments, str, A_WorkingDir, int, 1) 
		ExitApp
    }

    Return arguments
}	

StartSplashScreen() {
    SplashTextOn, , 20, PoE-TradeMacro, Merging and starting Scripts...
}

AppendCustomMacros(userDirectory)
{
	If(!InStr(FileExist(userDirectory "\CustomMacros"), "D")) {
		FileCreateDir, %userDirectory%\CustomMacros\
	}
	
	appendedMacros := "`n`n"
	extensions := "txt,ahk"
	Loop %userDirectory%\CustomMacros\*
	{
		If A_LoopFileExt in %extensions% 
		{
			FileRead, tmp, %A_LoopFileFullPath%
			appendedMacros .= "; appended custom macro file: " A_LoopFileName " ---------------------------------------------------"
			appendedMacros .= "`n" tmp "`n`n"
		}
	}
	
	Return appendedMacros
}

**Comment by Fone-Bone** [comment] 2017-08-09 12:37
Hi again

Forgot to write that I have searched for "_TradeMacroMain.ahk" but can not find any file with that name.

**Comment by Eruyome** [comment] 2017-08-09 12:55
![grafik](https://user-images.githubusercontent.com/16058242/29122445-acaa542c-7d12-11e7-8469-ca3444d6b7ca.png)

It's the actual file that is being executed, you should never execute it directly, therefore it is set to be hidden. All scripts are merged into this file. And don't try posting it's contents here, its over 11k lines long.

**Comment by Fone-Bone** [comment] 2017-08-09 13:15
Hi
Ok found it. Here it is. Changed ahk to txt file to be able to attach it. hope I have done it right.

[_TradeMacroMain.TXT](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/1211475/_TradeMacroMain.TXT)

**Comment by Eruyome** [comment] 2017-08-09 14:14
It seems that AdditionalMacros wasn't merged at all. Are you sure that AdditionalMacros.txt exists in your user folder? Can you show me that directory?

**Comment by Fone-Bone** [comment] 2017-08-09 19:43
Hi
default_AdditionalMacros.txt is in:
C:\Program Files (x86)\POE-TradeMacro-master\resources\ahk

Here is the file.

[default_AdditionalMacros.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/1212665/default_AdditionalMacros.txt)

**Comment by Eruyome** [comment] 2017-08-09 21:42
I didn't ask about default_AdditionalMacros, but AdditionalMacros in your user folder.
C:\Users\<YourUserHere>\Documents\PoE-TradeMacro\

**Comment by Fone-Bone** [comment] 2017-08-10 04:14
Sorry. I had deleted it and forgot everything about it. Now it is recovered from the bin.

Here it is:

[AdditionalMacros.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/1213647/AdditionalMacros.txt)

**Comment by Eruyome** [comment] 2017-08-10 13:22
That's the old file, from previous releases, not the new one that you need. THe new one is default_AdditionalMacros.txt which should be renamed to AdditionalMacros.txt and moved to your user folder on script start. Either when this default file was updated ot if your user folder doesn't have a AdditionalMacros.txt. If you have the correct file, then your macro works.

**Comment by Fone-Bone** [comment] 2017-08-10 15:40
Ha ha it works :-)

I renamed default_AdditionalMacros.txt and put it in dokumentfolder and everything works. I even opdated to v2.3.9 and that worked also. 

Thank you so much for your help. you are my hero :-)

**Comment by Eruyome** [comment] 2017-08-10 15:42
You're welcome

**Closed by Eruyome** 2017-08-10 15:42 UTC
