### ISSUE TITLE
Cannot read cookies

### ISSUE THREAD

**Issue by swedishstyle** [PoE-TradeMacro/POE-TradeMacro#884] opened 2019-01-12 01:02 UTC
POE Trade Macro output:
```
v2.12.3 
Cookie file found. 
Retrieving cookies failed. 
Windows Version: 10.0.17763 (10.0.17763), 64bit. 
Compiling 'getCookieData' script successful. 
Net Framework used for compiling: v4 
Internet Explorer: v11.253.17763.0
```

Cannot retrieve cookies manually per: https://github.com/PoE-TradeMacro/POE-TradeMacro/wiki/Cookie-retrieval

I cannot see any __cfduid or cf_clearance cookies, only _ga*, _gid and _gads in Chrome Developer menu. Same appears in Internet Explorer.

1. Delete your Internet Explorer/Edge cookies (the script can do this for you).
- No effect

2. Check that your IE security settings aren't low/disabled.
- Not low/disabled

3. Try repeatedly starting the script a few times if the bypass fails.
- No effect

4. Don't use any proxies, this can cause failing the bypass.
- Not using a proxy

5. Open the settings menu (right-click sytem tray icon) to manually set your cookies (you'll have to refresh them from time to time).
- Cannot get required information

6. Make sure to enable "Scripting" in IE and maybe add poe.trade to "Trusted Sites"(How to).
- It is enabled

7. You can also try disabling IE's protected mode. Win 7, IE10 and IE11.
- No effect

8. Temporarily disable your Antivirus Software/Firewall to make sure it's not interfering
- No effect

9. Lib\cURL
- Test script works:
`HTTP/1.1 200 OK
Server: nginx
Date: Sat, 12 Jan 2019 01:01:53 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
X-Frame-Options: DENY
Content-Encoding: gzip`

10. Cloudflare for POETrade
- DNS server change no effect
- No captcha/VPN

**Comment by stu177** [comment] 2019-01-12 01:03
Duplicate of #881 , #882 and #883

**Comment by swedishstyle** [comment] 2019-01-12 01:07
Apologies, a search for curl did not show me those issues

**Comment by Eruyome** [comment] 2019-01-12 01:20
Fixed.

**Closed by Eruyome** 2019-01-12 01:20 UTC
