### ISSUE TITLE
ERROR: Predicted search has encountered an unknown error (ctrl + d)

### ISSUE THREAD

**Issue by itsamemarkus** [PoE-TradeMacro/POE-TradeMacro#637] opened 2017-12-29 17:46 UTC
Hi, I'm using v2.7.4 and suddenly I get the error message

```
ERROR: Predicted search has encountered an unknown error
```
![2017-12-29 18_30_31-path of exile](https://user-images.githubusercontent.com/34944988/34443143-7da172c6-ecc7-11e7-9379-62ccd03a328d.png)

I currently get this error message with rare items only. It shows when I would usually get a price estimate (not the list with current, similar items on poe.trade).

Poe.trade and all search options work in my browser. Is there another third party site that delivers the estimates, that could cause this error?

AHK version: v1.1.27.00 (64 bit)
Windows version: Windows 10 Pro (with all current updates)

**Comment by Eruyome** [comment] 2017-12-30 08:28
2.7.3 still works for you?

Please make a search, then open `<TM folder>\temp\poeprices_log.txt` and post it's contents.

**Comment by itsamemarkus** [comment] 2017-12-30 10:08
No. 2.7.3 doesn't work for me. I now installed 2.7.4 and get the same error message. 

poeprices_log.txt

```
Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Abyss&i=&w=1",
        "encodedData": "",
        "league": "Abyss",
        "requestUrl": "https://www.poeprices.info/api?l=Abyss&i="
    },
    "error": 2
}
```

Item I used to perform the search on (but happens with all other rares too)

```
Rarity: Rare
Rift Circle
Two-Stone Ring
--------
Requirements:
Level: 57
--------
Item Level: 80
--------
+14% to Cold and Lightning Resistances
--------
+20 to Dexterity
+60 to maximum Life
+42% to Fire Resistance
+45% to Cold Resistance
```

Is there another folder except the extracted *POE-TradeMacro-2.7.4* and the automatically generated *PoE-TradeMacro* in Documents that I can delete, to have a fresh install?

**Comment by Eruyome** [comment] 2017-12-30 13:52
Your issue doesn't seem to be related to any messed up installation.

`"encodedData": ""` is empty, I'll have to see what causes this.

the same temp folder should also have the files:

* encodeToBase64.txt
* base64ItemText.txt

Please show those also. I have actually found a small issue which didn't cause the search to fail for me though.

**Comment by itsamemarkus** [comment] 2017-12-30 14:02
Thanks for the fast response.

encodeToBase64.txt is actually empty (0kb) and is named **encodeToBase64.txt.txt** (see screenshot, I did not rename any file)

base64ItemText.txt is not generated after pressing ctrl + d

itemText.txt content

```
Rarity: Rare
Rift Circle
Two-Stone Ring
--------
Requirements:
Level: 57
--------
Item Level: 80
--------
+14% to Cold and Lightning Resistances
--------
+20 to Dexterity
+60 to maximum Life
+42% to Fire Resistance
+45% to Cold Resistance
```

Screenshot of my temp folder

![2017-12-30 14_58_53-temp](https://user-images.githubusercontent.com/34944988/34454748-502185ec-ed72-11e7-9d5f-b41c66d78c75.png)

**Comment by Eruyome** [comment] 2017-12-30 14:48
Good, then open a windows prompt/terminal/console and execute:

`certutil -encode -f "D:\Users\Eru\Documents\GitHub\POE-TradeMacro\temp\itemText.txt" "D:\Users\Eru\Documents\GitHub\POE-TradeMacro\temp\base64ItemText.txt" & type "D:\Users\Eru\Documents\GitHub\POE-TradeMacro\temp\base64ItemText.txt"`

but make sure to replace the file paths and make sure that `itemText.txt` still exists with the posted contents.

**Comment by itsamemarkus** [comment] 2017-12-30 15:43
This is the output

![2017-12-30 16_39_28-administrator_ eingabeaufforderung](https://user-images.githubusercontent.com/34944988/34455464-0c291fc2-ed80-11e7-9ada-f90ebae33f5b.png)

Just curious: might the weird file ending of encodeToBase64 **.txt.txt** that is created by default be a cause of the error?

**Comment by itsamemarkus** [comment] 2017-12-30 15:48
Update: After I executed the command above, it seems to work again.  Weird :D 

Thanks for the help. But I'm afraid that this would happen again, if I reinstall the TradeMacro

**Comment by itsamemarkus** [comment] 2017-12-30 16:13
Don't know if this helps, video of a fresh 2.7.4 install and how the contents of the temp folder change.

https://www.dropbox.com/s/hfka8tzhjb8fjno/poe_trade_macro.flv?dl=0

**Comment by Eruyome** [comment] 2017-12-30 16:37
Btw, also german here but I'll keep this english if possible.

Have you tried the linked dev version? While the `.txt.txt` isn't an issue on my end I have fixed it in the dev version. Can you reproduce "fixing" the issue by using the certutil command manually? That itself doesn't make any sense to me.

**Comment by itsamemarkus** [comment] 2018-01-02 02:46
I don't know how to describe it best, I think the Macro doesn't update the encoded item data and always shows the same estimate, after I run the command manually. Maybe this video helps

https://www.dropbox.com/s/06wnjykitmhpa3b/poe_trade_macro2.flv?dl=0

Does this happen for someone else, or is it only me? I can't pinpoint what made the Macro not work any more. I tried deleting, and reinstalling the Macro and even reinstalled AutoHotkey.

**Comment by Eruyome** [comment] 2018-01-02 12:01
While I have no idea if it helps, you're still not using the dev version that I lnked https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip

**Comment by itsamemarkus** [comment] 2018-01-02 16:33
Sorry, thought you wanted me to try with official release. Dev version shows same error too.

**Comment by TheGambler92** [comment] 2018-01-05 23:18
Hello,

I am also getting the same errors as mentioned above. I tried to do a price prediction for at least 20 different rare items and I am getting for every single rare item the same error.

**Comment by Eruyome** [comment] 2018-01-06 16:00
cURL could be blocked but then you would probably get quite a few more errors.
The issue described here is a different one, could you also show me the poeprices_log.txt in the temp folder?

I'll soon have time to put a dev version together that has some debug output to find the actual issue causing the encoded item data to be missing.

**Comment by TheGambler92** [comment] 2018-01-06 17:02
Hey Eruyome,

here is the poeprices_log.txt. I really dont know, why I always get an error. Is there anywhere a log, where the exact error message is written down and I can provide it to you?

```
Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Abyss&i=&w=1",
        "encodedData": "",
        "league": "Abyss",
        "requestUrl": "https://www.poeprices.info/api?l=Abyss&i="
    },
    "error": 2
}
```

**Comment by Eruyome** [comment] 2018-01-06 22:18
No, I'll have to add some logging for that special case here.

**Comment by TheGambler92** [comment] 2018-01-09 21:21
And do you got any news regarding this special case? Would be really cool, if I also can use the price prediction feature. :)

**Comment by Eruyome** [comment] 2018-01-11 00:31
I have added some debug output to this version here, try it.

You'll get a windows console window showing whether the certutil command was successful and an AHK console window showing the certutil commands (fullpath and relative path) and the encodedData length at some places in the code. You'll ahve to enable `Debug output`in the settings though.

https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/encodeDataDebug.zip

**Comment by TheGambler92** [comment] 2018-01-11 16:53
The command line is instantly closing and I am still getting the error. How can I enable the Debug ouput settings?

**Comment by Eruyome** [comment] 2018-01-11 20:15
Settings menu, first tab.

![image](https://user-images.githubusercontent.com/16058242/34845265-99c9efda-f714-11e7-8db8-7f3a20b0d6e6.png)

**Comment by TheGambler92** [comment] 2018-01-11 20:42
Okay I have activated it, but the console is still instantly closing. Can I send you any file or what should I do?

**Comment by Eruyome** [comment] 2018-01-11 21:47
Which console are you talking about?
There should be this one sitting somewhere in the background, after restarting the script:

![image](https://user-images.githubusercontent.com/16058242/34848990-23e63ef6-f721-11e7-9fc2-ac8515703145.png)

And the windows one that should open when doing a predicted search. If this one simply closes, there was probably and error while executing the `certutil` command. 
But the AHK console window should show the executed command.

**Comment by Eruyome** [comment] 2018-01-11 21:52
You can copy the command and execute it in a seperate windwos console. Doing it like this should show any errors instead of simply closing the console window.

![image](https://user-images.githubusercontent.com/16058242/34849199-e0ae9baa-f721-11e7-8069-633f5799a309.png)

In this case I'd execute the first line which uses the full file paths.
```
certutil -encode -f "D:\Users\Eru\Documents\GitHub\POE-TradeMacro\temp\itemText.txt" "D:\Users\Eru\Documents\GitHub\POE-TradeMacro\temp\base64ItemText.txt" & type "D:\Users\Eru\Documents\GitHub\POE-TradeMacro\temp\base64ItemText.txt"
```

**Comment by Eruyome** [comment] 2018-01-12 19:19
Whats your Windows version? Anything special about it?

**Comment by itsamemarkus** [comment] 2018-01-12 19:22
This is my console output for a failed ctrl +d

![2018-01-12 20_17_25-console debugid _console_](https://user-images.githubusercontent.com/34944988/34891398-bcd2a474-f7d5-11e7-98fb-c4b22412e83f.png)

Just a guess, maybe certutil isn't executed with admin privileges? This is my cmd -> certutil output as admin and as non admin

![2018-01-12 20_19_16-nvidia geforce overlay](https://user-images.githubusercontent.com/34944988/34891554-3fe68e8e-f7d6-11e7-8787-a543de090d10.png)

**Comment by TheGambler92** [comment] 2018-01-12 19:24
I have installed Windows 7 Home Premium, so nothing special. I think I also executed the command as a NON Admin.

**Comment by Eruyome** [comment] 2018-01-12 19:30
Can you execute certutil with the non admin console when using the full path `C:\Windows\system32\certutil.exe`?

**Comment by TheGambler92** [comment] 2018-01-12 19:31
Yes that works for me. but also the cmd executed as an admin is working now. That's a workaround and I am getting now the price predicition. :) Thx for your help.

**Comment by Eruyome** [comment] 2018-01-12 19:39
Please use that again https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/encodeDataDebug.zip
and tell me if the script tells you at start whether you (or the script) has admin privileges.

**Comment by itsamemarkus** [comment] 2018-01-12 20:50
yes, it requires admin privileges to start

**Comment by Eruyome** [comment] 2018-01-12 21:10
https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/encodeDataDebug.zip

Try it again and tell me if the search works. If not, edit `%TM-Folder%\resources\ahk\PoE-ItemInfo.ahk` and change line 10488 from:

```
	If (not StrLen(stringBase64) and false) {
```
to 
```
	If (not StrLen(stringBase64)) {
```

**Closed** 2018-05-23 02:19 UTC
