### ISSUE TITLE
Always Error Cookie Data

### ISSUE THREAD

**Issue by ZeusTTV** [PoE-TradeMacro/POE-TradeMacro#167] opened 2016-12-26 15:27 UTC
Cant run this Version , pls fix it.  Always Reset Data and same Error...

**Comment by Eruyome** [comment] 2016-12-26 15:55
Not sure that I actually can fix it. Also you have to provide way more than just "can't run this version". I'm a bit tired of repeating myself. What error message did you get if any, what steps exactly did you take to resolve this issue, what windows version are you on, what IE version, are you using any proxy? Anything else network realted that's a bit unusual (like proxies)? What macro version did you try, does any of them work for you?

**Comment by ZeusTTV** [comment] 2016-12-26 16:03
1.4.0-beta-2  was fine , the new Version cant run . After Starting it ,  bypass window pops up and i cant change the data or run it with that new autofill script
maybe im to sutpid but yesterday was everything fine.

**Comment by Eruyome** [comment] 2016-12-26 16:49
Are you sure you can't get it working by rebooting/deleting cookies etc? The new release is the same as 1.4.0-beta-2 except better error handling/feedback and an totally unrelated fix for some divination cards. You're not the only one where it suddenly didn't work anymore but could get fixed https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/165.

**Comment by ZeusTTV** [comment] 2016-12-26 17:52
im done , i wait till next release....  thx for help

**Comment by Eruyome** [comment] 2016-12-26 18:07
Not sure a next release will change anything though. The current [master code](https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/master.zip) has optimized error handling: http://imgur.com/YK2NVDg, In fact your lacking report (of information) made me rewrite this :p Maybe this can tell me something.

**Comment by sicero316** [comment] 2016-12-26 19:48
It seems to every time i run Run_Only_This it is getting wrong cookie, need manual set up option for:
This what i get in cookie file /temp
useragent=Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; Win64; x64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729)
cfduid=ded9af585595c7a20d1b2e4257b8578d51482776955
cf_clearance=f44ddef909aabe446f7131b41e6b14b05dce19b4-1482777004-604800
This i get from .ahk:
HttpObj.SetRequestHeader("Cookie","__cfduid=d7f43d2c175558f90722db927fc02b2861482304811; cf_clearance=831c768983c53fdd7eb0e06414f3fd6391bfb7a7-1482420070-604800")
I went to browser to see(ctr shift i):
d9230ad28270ceffee1291756ca4ac0391482779308
d82bc2ba54ea1caa2d4465d6a3c2bcae89503ee2-1482779312-604800

When i fix value in cookie file it changing it back on wrong numbers....
sooo idk.

**Comment by sicero316** [comment] 2016-12-26 19:56
In 1.3 version all was fine until i update to 1.4.1

**Comment by Eruyome** [comment] 2016-12-26 20:20
I don't really get what you're trying to say.

First of, are you trying to compare your Chrome/Firefox user agent and cookies with the Internet Explorer cookies (from the script)? Of course this will fail and will be different. 

Secondly, those cookies aren't generated by some algorithm, they are directly taken from Internet Explorer, they are correct.

> This i get from .ahk:

What are you trying to say here? Are you still editing the script files (which you shouldn't do)?
If you want to manually test cookies, use version 1.3.0 and tell me if you have any success. If you do try your Chrome/Firefox cookies first, then the ones from Internet Explorer.

**Comment by Eruyome** [comment] 2016-12-27 13:37
@ZeusTTV @sicero316 Please test the latest release and close this issue if your problems are resolved.

**Comment by loadingx86** [comment] 2016-12-27 13:51
http://image.prntscr.com/image/ac578acec442494ab559fc8c41f47198.jpeg

**Comment by Eruyome** [comment] 2016-12-27 16:28
@loadingx86 you know, there is advice on how to solve this, there's a link to the FAQ for a reason (more advice), I can't help much if you don't tell me what you did to resolve this. For all I know you started the .ahk file once and gave up because it said it failed.

**Comment by Servion033** [comment] 2016-12-28 08:32
@Eruyome I (and a few of my friends) have exactly the same issue as @loadingx86 

- Restarted the script multiple times, but nothing changed
- Reset IE settings to default
- Not using any proxies or similar

After using the "Delete cookies" button in the bottom about 10 times and it still failing, I tried to executed the PoE-TradeMacro_(Fallback).exe, but got an error, that getCookieData.exe is not working properly and therefore was ended by Windows.

Then I used the manual steps to enter my cookie data in the settings and now everything is working fine. However, as this data is changing somewhat often, it would be great if you can look into this issue.

**Comment by Eruyome** [comment] 2016-12-28 12:21
@Servion033 Did 1.4.1 work for you? Just had someone in discord, we tried everything we could to no avail, he knew 1.4.1 worked for him, so he started it (worked), then started 1.5.0 again and now it works, too...

What was the exact error message you get when using the .exe? And running `getCookieData.exe` only fails when using the .exe, not when using .ahk? Does it work when you execute it manually?

**Comment by Servion033** [comment] 2016-12-28 12:56
@Eruyome 
The getCookieData.exe error was caused by me not starting the program with administrative permissions, so you can ignore that. Sorry!

In 1.4.0 it worked fine by copying the cookie data from Chrome to the config file (which is working for 1.5 also). In 1.4.1 nothing worked.

When executing the .exe I now get the same message as when using the .ahk file: "Bypassing poe.trades CloudFlare protection failed!" and the following information:

- Cookie file found. 
- Retrieving cookies successful. 
- Windows Version: 10.0.14393 (10.0.14393), 64bit. 
- Compiling 'getCookieData' script successful. 
- Net Framework used for compiling: v4 
- Internet Explorer: v11.576.14393.0

**Comment by Eruyome** [comment] 2016-12-28 13:13
Maybe I can find a solution to read Firefox/Chrome cookies, but I need help for this, not enough knowledge (c# for example). https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/173

**Comment by sicero316** [comment] 2016-12-28 20:39
Sry about that, i'm bad at explaining things.
First: I was editing TradeMacro.ahk by myself, injecting values from poe.trade cookie, those 3 values you can see in browser like in that guide(after ddos happen and cf implements their protection).
1.1: After update happen with macro, i remove old cookie and get new one, thing i was trying to say this automatic cookie parsing should be optional, coz it can ruin config in some way. I was trying to set macro like in guide, but numbers i was getting in that text file was incorrect.
Second: I don't know how it can be correct if i have totally cut-out (os component) IE for security reason. I use Firefox.
After some manipulations with TradeMacro.ahk it start working again. Changes default values of agent and other two.

**Comment by Eruyome** [comment] 2016-12-29 14:44
Are you telling me that you have completely uninstalled/removed Internet Explorer from your system? I'm not sure that's even possible (complete removal of all components) since there should be some software that uses IE engine. Simply uninstalling should be possible. What you use doesn't matter. As long as the c# script can open a browser window (hidden, using IE engine) and open poe.trade to generate cookies and read them + useragent it doesn't matter if you haven't opened IE in the last 20 years.

Making the automatic retrieval optional makes no sense, since it simply works for the majority of people. It doesn't ruin any config, also. Use automatic cookies and do nothing else or use manual cookies and completely ignore the `cookie_data.txt`. If you don't want to (or can't) use automatic cookies you have to do extra work anyway (get cookies/useragent and paste them to settings), so opening the settings and checking `overwrite automatic cookies` isn't asking too much. Why should this method be the default?

**Comment by Eruyome** [comment] 2017-01-03 20:58
I'm closing this issue since nobody seems to follow it anymore. If anyone still has problems and can give me more feedback just reopen it.

**Comment by Servion033** [comment] 2017-01-04 14:17
I am still following this. No one I know has a working macro right now. The only solution is to start it up, go to the options, change the cf_clearance (daily) and then restart the tool (is there a way to not have to restart after changing the settings?).

If you need any further information I'm glad to test stuff and provide more feedback.

**Comment by Eruyome** [comment] 2017-01-04 14:33
Could you test the newest code on the master banch?
Well, I probably could write something to trigger reading the cookies (manual ones) without restart. That's something I can do when I have the time.

**Comment by Servion033** [comment] 2017-01-04 16:08
Downloaded the Macro again and now it's working! Did you change anything?

**Comment by Eruyome** [comment] 2017-01-04 16:11
I think I only changed how the cookies are deleted, it wasn't reliable at all, depending on some IE settings.

**Closed by Eruyome** 2017-01-04 16:11 UTC
