### ISSUE TITLE
Trade Macro continuously spams mouse clicks

### ISSUE THREAD

**Issue by CamelFace** [PoE-TradeMacro/POE-TradeMacro#625] opened 2017-12-21 15:14 UTC
AHK version: 64-bit
Windows version: Windows 10 64-bit

I'm new to this, but I used this macro last season with no problem.

Now whenever I open it, the programs spams mouse clicks.  While in game I can only hold down the mouse for a few seconds before it clicks outside of it.  This continues even after closing the game and shutting down the Macro.  Reloading and suspending don't do anything.

It only seems to stop when I log out of my windows username or restart the computer.

Any suggestions?

**Comment by aRTy42** [comment] 2017-12-21 15:23
I'm not aware of any function that uses a click.
Do you have any autoclick macros in the "<Documents>\PoE-TradeMacro\CustomMacros" folder?

Please also have a look at "Show all assigned Hotkeys" in the rightclick context menu and post a screenshot of it.

**Comment by CamelFace** [comment] 2017-12-21 15:47
https://i.gyazo.com/a43c4356641b0e378f7d9edbe67e4140.png

Link to the gyazo image.  I haven't made any new hotkeys.  This should be a clean install.

**Comment by aRTy42** [comment] 2017-12-21 16:30
Do you have a mouse or keyboard with macro keys?

**Comment by CamelFace** [comment] 2017-12-21 16:37
I never made any.  Another reason I'm surprised that things stopped working between seasons.

**Comment by CamelFace** [comment] 2017-12-21 16:50
I've gone through and tried some of the older versions.  They don't seem to deprioritize PoE quite as often, but it's still a few times per minute.  The newest version does it every 5 seconds.

**Comment by aRTy42** [comment] 2017-12-21 17:24
Currently no idea, sorry.

**Comment by Eruyome** [comment] 2017-12-26 15:37
I also have no idea, but if it persists even after closing the macro I can see no reason why it would be caused by the macro itself.

**Comment by Eruyome** [comment] 2018-01-05 01:16
Did you find the issue?

**Closed** 2018-03-17 04:21 UTC
