### ISSUE TITLE
Error after new update

### ISSUE THREAD

**Issue by czaja125** [PoE-TradeMacro/POE-TradeMacro#485] opened 2017-09-02 12:46 UTC
![macros](https://user-images.githubusercontent.com/14146261/29995592-763e3ed8-8fed-11e7-943b-06c545270bbd.jpg)

**Comment by aRTy42** [comment] 2017-09-02 13:27
Are you using the CustomMacros file? In the \CustomMacros folder, there should be exactly one file for personal macros. Are there multiple files in the folder?

In the one file that should be there, the line
> CM_ExecuteCustomMacrosCode_Label:
should only appear once.
Did you put personal code there and maybe duplicated the line?

**Comment by czaja125** [comment] 2017-09-03 11:21
No i just download new update. Don't use personal codes.
found CM_ExecuteCustomMacrosCode_Label: in two folders: 
![macros](https://user-images.githubusercontent.com/14146261/30002462-8927669c-90aa-11e7-8200-a8c34e0b38ab.jpg)

![macros](https://user-images.githubusercontent.com/14146261/30002475-bef131c2-90aa-11e7-8f50-33fa3a8aa854.jpg)
try re download ahk and trade macro still the same error.

**Comment by czaja125** [comment] 2017-09-03 11:24
bad photos

![macrosss](https://user-images.githubusercontent.com/14146261/30002485-dfafa9e8-90aa-11e7-9b7d-e3688c857cdd.png)

![macrosss](https://user-images.githubusercontent.com/14146261/30002505-1e889f4e-90ab-11e7-866a-75493967e1a4.png)

just in this two folders.

**Comment by Eruyome** [comment] 2017-09-03 11:33
Edit `_TradeMacroMain.ahk` (hidden file) and search for `CM_ExecuteCustomMacrosCode_Label`, I guess that for some reason the file `customMacros_example` is being appended/merged twice instead of once.

**Comment by Eruyome** [comment] 2017-09-03 11:34
Aside from that, you're looking in the wrong palce, look in `%USERPROFILE%\Documents\PoE-TradeMacro\`.

**Comment by czaja125** [comment] 2017-09-03 11:37
> Aside from that, you're looking in the wrong palce, look in %USERPROFILE%\Documents\PoE-TradeMacro\.

Thank you :) It was duplicated folders. Its working now,

**Comment by Eruyome** [comment] 2017-09-03 11:44
Duplicated folders? Can you elaborate that? Was this caused by the script or did you mess with it?

**Closed** 2017-09-05 17:10 UTC
