### ISSUE TITLE
"No Item Found." when trying to search w/ ctrl+d

### ISSUE THREAD

**Issue by OziumAir** [PoE-TradeMacro/POE-TradeMacro#1056] opened 2019-12-14 19:07 UTC
I'm getting a return of "No Item Found." when trying to search w/ ctrl+d.  It was just working earlier before Trade Macro started locking up.  After a reboot i'm now getting this error.

**Comment by Versalkul** [comment] 2019-12-14 19:30
Me and a friend of mine get the same error.

**Comment by sumonetwo-poe** [comment] 2019-12-14 19:35
+1 getting this error, as is my friend

**Comment by Jigglyy** [comment] 2019-12-14 19:50
same, what's up with that?

**Comment by nimutu** [comment] 2019-12-14 19:50
same here

**Comment by Freakey1** [comment] 2019-12-14 19:56
Same.

**Comment by jessicamorin** [comment] 2019-12-14 20:12
I have the same error.

**Comment by Eruyome** [comment] 2019-12-14 20:15
Fixed in the new v2.15.5

**Closed by Eruyome** 2019-12-14 20:15 UTC

**Comment by KofiAddict** [comment] 2019-12-14 20:21
The update gets stuck in a loop not being able to update from 2.15.4 to 2.15.5 gonna try to redownload macro from site

**Comment by KofiAddict** [comment] 2019-12-14 20:25
Redownloaded from github, got update prompt anyway, cancelled it and it works

**Comment by Eruyome** [comment] 2019-12-14 20:32
This was caused by an incorrect version tag, redownloading fixes it.

**Comment by KofiAddict** [comment] 2019-12-14 20:33
You are a legend, thank you
