### ISSUE TITLE
TradeMacro not Working cURL+Cookie issue

### ISSUE THREAD

**Issue by Sikarar** [PoE-TradeMacro/POE-TradeMacro#883] opened 2019-01-12 00:38 UTC
TradeMacro was working fine but suddenly stopped working today. It says there is no item listed no matter what I am searching for.

It seems to be saying that cURL and Cookies failed but I don't quite understand what those mean exactly. I have tried to whitelist TradeMacro in my anti-virus (McAfee) but it didn't help.

Information the script is asking me to provide in my report:
v2.12.3 
Cookie file found. 
Retrieving cookies failed. 
Windows Version: 6.3.9600 (WIN_8.1), 64bit. 
Compiling 'getCookieData' script successful. 
Net Framework used for compiling: v4 
Internet Explorer: v11.0.9600.19236

**Comment by stu177** [comment] 2019-01-12 00:44
Duplicate of #881

**Comment by Dravick06** [comment] 2019-01-12 00:55
I may be having a related problem, Macro gets stuck at collecting cookie data and never gets past that popup. Unable to use it at all right now. I've moved the folder, tried doing a fresh download. Nothing fixes the problem. Was working fine yesterday before the update.

**Comment by Eruyome** [comment] 2019-01-12 01:20
Fixed.

**Closed by Eruyome** 2019-01-12 01:20 UTC
