### ISSUE TITLE
New version (v2.0.10) broke hotkey tooltips

### ISSUE THREAD

**Issue by artofvs** [PoE-TradeMacro/POE-TradeMacro#326] opened 2017-04-08 07:23 UTC
Not sure what was the problem here, but after updating to 2.0.10 tooltips stopped showing up.
Restarting macro, windows and downgrading to v2.0.9 did not help.
But downloading newest version of POE-ItemInfo (2.6.01) and replacing POE-TradeMacro\resources\ahk\POE-ItemInfo.ahk file with the one from POE-ItemInfo somehow fixed issue.

**Comment by InfiniteIce** [comment] 2017-04-08 13:04
Confirming this issue as well, and replacing the file mentioned above didn't seem to work for me (replaced with file from ARTY42 iteminfo repository.)

**Comment by Eruyome** [comment] 2017-04-09 07:12
Check the new version again.

**Comment by ogier** [comment] 2017-04-09 11:44
I'm also unable to see tooltips (2.0.11). I was previously using the non-admin script, which seems to be missing now, if that matters.

**Comment by ogier** [comment] 2017-04-09 11:47
Oh derp. Found my issue. Somehow my borderless windowed display option was reset. Ignore my report, works fine in borderless windowed.

**Comment by Eruyome** [comment] 2017-04-09 15:22
@InfiniteIce, @artofvs what about you guys?

**Comment by artofvs** [comment] 2017-04-09 15:40
I updated to 2.0.11 from modified working 2.0.10 and it works too

**Comment by Shirest** [comment] 2017-04-10 04:25
They are still broken for me as well - running newest build on windowed border less.

**Comment by Eruyome** [comment] 2017-04-10 04:50
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/311#issuecomment-292806728 Could you take a look at this issue here? Do you have the same issue or a different one?

**Comment by Shirest** [comment] 2017-04-10 04:56
I actually just realized it's the trade macro that's not working, ctrl c is working fine as are all the other item info scripts, but none of the trade macros are. Should I still attempt your test scripts in #311?

**Comment by Eruyome** [comment] 2017-04-10 08:03
You seem to have a different issue then. Are you sure that you're not making any mistakes in running/using TradeMacro? What does "no TradeMacro hotkeys are working" mean? Really not a single one of these or just the tooltips?

|Shortcut|Description|
|---	|---	|
| ctrl+c      | See item info (via PoE-ItemInfo). 
| ctrl+d      | Search item on poe.trade.
| ctrl+alt+d  | Advanced item search. 
| ctrl+i      | Opens a text input where you can type an item name to search for.
| ctrl+w      | Open the items wiki page. 
| ctrl+q      | Open the item search on poe.trade instead of showing a tooltip with results.
| ctrl+e      | Show item age (own listed items).
| ctrl+l      | Switch leagues.

**Comment by Shirest** [comment] 2017-04-10 08:08
Just tested-- The only macro that works for me is ctrl + c. For more information, I have been using every version up until this latest push without any problems. After updating it stopped working to where AHK wouldn't compile the scripts. I assumed that something went wrong during extracting and downloaded a fresh version. AHK compiled and then I ran the script after editing the league to hc, then ran. No compilation errors, All AHK commands work (right clicking the icon and selecting an option) just the core features. 

By the way thank you for providing such an awesome tool!

**Comment by Shirest** [comment] 2017-04-10 08:18
Alright, it's on me somehow. If I find the conflicting program I'll let you know! Sorry for the trouble.

**Comment by Eruyome** [comment] 2017-04-10 08:23
Have you tried without compiling anything? It's not necessary in any way.

**Comment by Shirest** [comment] 2017-04-10 08:25
yea, just running only Run_TradeMacro

**Comment by Shirest** [comment] 2017-04-10 08:32
Can't figure it out, so I'm just going to run on 1.7.2 which I have archived which works just fine! Thanks for trying to figure it out with me though.. I guess it is possible something in windows insider broke something in the newer version as I did just install a new build yesterday when you pushed out the new versions.

**Comment by aRTy42** [comment] 2017-04-13 07:48
Just wanted to add that the windows 10 creator update introduced the so called "game bar" feature as part of the xbox app and Path of Exile is one of the recognized games for it (see discussion [here](https://www.reddit.com/r/pathofexile/comments/653n9h/trademacro_windows_10_creator_update/)). This might influence how the whole fullscreen/borderless/windowed settings are handled.

**Comment by Eruyome** [comment] 2017-04-18 10:16
So, haven't checked TradeMacro for a while because I had some hardware issues. Anyway, it seems likely that this could cause some issues but since I don't have any windows 10 here that may be a bit hard for me to judge and test.

**Comment by frans-de-waal** [comment] 2017-04-19 17:49
I'm having similar issues where the tooltip for the item info an quick search only show once or twice after loading the script. Sometimes I can get it to work by reloading the script but this isn't very consistent. I'm running the steam client on Windows 7

**Comment by binbinhfr** [comment] 2017-04-19 18:17
you should try to install the non-steam client. It solved my problem, but I still did not understand why...

**Comment by dein0s** [comment] 2017-04-19 19:59
I'd guess it can be somehow related to the steam overlay, not the game client itself.

**Comment by Eruyome** [comment] 2017-04-19 20:03
It's weird nonetheless, since not everyone using steam has this issue, like myself.

**Comment by binbinhfr** [comment] 2017-04-19 20:30
I tried to disable any steam overlay or streaming feature, but nothing changed. It seems like if the steam-version of the game does not set the windowed-fullscreen mode, but the true-fullscreen mode instead.

**Comment by shiftymcfire** [comment] 2017-05-13 17:47
@Eruyome 
> aRTy42 commented on Apr 13
Just wanted to add that the recent windows 10 creator update introduced the so called "game bar" feature as part of the xbox app and Path of Exile is one of the recognized games for it (see discussion here). This might influence how the whole fullscreen/borderless/windowed settings are handled.

Just wanted to add that I had the same issues immediately after installing the Creator's update. Mercury Trade worked fine, but nothing I did could seem to bring the Trade Macro to the foreground (changing from fs windowed to windowed, changing resolution, installing standalone, etc).

After following the steps [here](http://www.windowscentral.com/how-disable-and-remove-game-bar-windows-10-creators-update) **upto and including** disabling Game Monitoring and quickly rebooting, everything is back to working order again.

I have a feeling that the DVR functions and/or gamebar overlay from the Creator's Update is somehow forcing itself on the top of the window stack and pushing the AHK tooltips one layer or more down the stack, and is causing them to pop up behind the POE client (Standalone and Steam had the same issue for me).

**Comment by Eruyome** [comment] 2017-05-13 18:11
Thanks for the report. I was quite sure that it was caused by that update, but I don't know whether there's any way to solve this via AHK. In the worst case I just have to mention this in the FAQ.

**Comment by Eruyome** [comment] 2017-06-05 13:57
I'll close this for now, just reopen it or request it if there still are issues.

**Closed by Eruyome** 2017-06-05 13:57 UTC
