### ISSUE TITLE
Parsing the currency data from poe.ninja failed

### ISSUE THREAD

**Issue by xhriiis** [PoE-TradeMacro/POE-TradeMacro#613] opened 2017-12-14 16:32 UTC
AHK version: v2.6.3 (Downloaded directly from github using the latest version link)
Windows version: Windows 10

Upon starting the script I get this error since yesterday. 
I have tried start as admin and reinstalling the script completly. 
I have checked if poe.trade or poe.ninja or GGG's site are down but they are not and the script is working fine for other friends.

![tradeerror](https://user-images.githubusercontent.com/34548785/34002858-0dbab76c-e0f4-11e7-8a9f-be58dca2598e.png)
 
Best regards,

Chris

**Comment by Mobsy6** [comment] 2017-12-14 17:02
Would love an update on this too, experiencing the same problem :(

**Comment by Eruyome** [comment] 2017-12-14 22:45
This error is caused when you can't download this  here http://poe.ninja/api/Data/GetCurrencyOverview?league=Abyss.

I don't have that issue, many others don't seem to have it. My first guess would be that the issue is on your end. Does it always show up or just here and there?

**Comment by simon-menard-lariviere** [comment] 2017-12-15 01:12
I had the same problem since the Abyss league and for now I seem to have fixed it.
For some reasons, I didn't have any league selected. I went to my setting, set tmpLeague and pressed OK.

**Comment by xhriiis** [comment] 2017-12-15 11:58
@Eruyome It always shows up, Im downloading the new version right now and hope that fixes it :)

**Comment by uszkay** [comment] 2017-12-15 21:53
A few patches back (2.6.2 perhaps) the League choice went from tmpstandard/tmphardore to abyss/hardcoreabyss.
Now the League choice is back to usual tmpstandard and tmphardore.

If you've chosen the differently named League, like I did back then, then you'll have this error now.

If you go back to the options now and your League is empty, just select your appropriate league from the dropdown menu and it'll work again just fine. I've tested with closing the script/macro and re-opening and it still saved the correct league.

**Comment by Eruyome** [comment] 2017-12-26 17:08
@xhriiis Does uszkeys advice solve your issue?

**Comment by Eruyome** [comment] 2018-01-05 01:20
uszkeys advice should be the solution for everyone experiencing this.

**Closed by Eruyome** 2018-01-05 01:20 UTC

**Comment by duckfart** [comment] 2018-01-18 10:48
have the same problem.. been searching for a solution, can't find any
![asdasd](https://user-images.githubusercontent.com/35562776/35094442-35524342-fc80-11e7-9054-359a978e565e.JPG)

**Comment by Eruyome** [comment] 2018-01-19 02:58
Your script isn't fully loaded. Are you using a fresh copy/install of TradeMacro, no edited files? Do you get the poeninja error every time without exception?

**Comment by duckfart** [comment] 2018-01-19 16:49
after initializing script.. parsing error pops up, and when i press OK. nothing happens. parsing error is still there.

![asdasd2](https://user-images.githubusercontent.com/35562776/35161612-aee48a16-fd7b-11e7-8100-b1182f80ae74.jpg)

**Comment by kinho3** [comment] 2018-01-19 17:03
I have the same problem and i dont change anything. =/
i've installed again, but still with this problem.

**Comment by duckfart** [comment] 2018-01-21 04:28
i think its just from the poe.ninja site.. when i have the parsing error the poe.ninja have this confirmation that says click to confirm you're not a robot.. 

i always check prices so i always open poe.ninja site and i noticed that there's no confirmation anymore. then i tried opening my trade macro to check if it works and it works!! :D

**Comment by Eruyome** [comment] 2018-01-21 12:51
Always check if you can actuyll access poe.ninja when this error occurs, it's the most likely reason.
