### ISSUE TITLE
Extremely slow initialization and CTRL + D searches

### ISSUE THREAD

**Issue by joprut** [PoE-TradeMacro/POE-TradeMacro#738] opened 2018-06-07 19:42 UTC
AHK version:  v1.1.29.01
Windows version: 10 Home 10.0.16299 Build 16299

All was going well, I've been using Trade Macro for at least a year and never had a problem. Now it takes Forever to initialize. from merging scripts to Paying Respects to the cynical Brit there is a noticeable slowdown and from then on it is very long until it disapears. when the script is loaded, when i press CTRL+C it returns a result instantly but when i press CTRL+D it takes forever.(It still brings up results though). I've reinstalled AHK and trade macro, Cleared Cookies on all browsers and it still continues to take that long.

Poe.trade is fast and responsive on browser.

internet connection : 150 Mbps Download ,15 Mbps Upload

Update : Friends who live in the same area as me do not have this problem.
Update: Right clicks on the icon take a long time top open menu and when I open, it causes the program to stop responding for a good few seconds.
Update: poe.trade is the one i use for everything except rare item pricing which is poeprices.info.
rare item pricing works just fine.
Update: it started yesterday as well (june 6 2018)
Help me resolve that issue please :)

**Comment by aRTy42** [comment] 2018-06-08 01:33
Which site are you requesting with Ctrl+D and what kind of item are we talking about? poeprices.info with the machine learning for rares for example? poe.ninja for currency? poe.trade for everything?

(Ctrl+C is a local thing, it does not query online resources, so that one should never be delayed)

**Comment by joprut** [comment] 2018-06-08 01:37
Updated initial comment for further informaition :)

**Comment by ScubaSt3v3** [comment] 2018-06-08 02:15
I'm having the same issue as OP.
- The item info works fast as you said (Local query).
- When price checking from poe.trade, there is a 30-40 second delay. It eventually brings up your query if you wait for it.
- Curl.exe goes "Not Responding" in task manager during the query, closes, then starts up again a few times until it can finally pull from poe.trade.

**Comment by aRTy42** [comment] 2018-06-08 02:20
This technical aspect is something for Eruyome. I can give you the advice I gave codyst78 in discord though: Try Ctrl+Q until either the issue resolves itself (if it is actually due to the connection) or the problem is found.

**Comment by joprut** [comment] 2018-06-08 02:21
Thank you very much for the help everyone :)

**Comment by Zeronthe** [comment] 2018-06-08 02:44
I also have this issue, but it takes an eternity for it to pull anything up in Crtl+Q as well. It's like the entire script is hanging for no reason. Poe.trade is fast, same with my internet and other associated things. 

It just started happening yesterday. Also takes an eternity to merge/initialize, going back a few versions doesn't seem to resolve, niether does doing a clean install of the script via deleting stuff in docs/temp/apapdata/etc.

**Comment by siisjuu** [comment] 2018-06-08 07:35
I've had this kind of issue since like 2 days ago. I even made a post on AHK reddit because I thought the problem was on my end (None of my friends had this issue, post can be found here: www.reddit.com/r/AutoHotkey/comments/8p9p0l/autohotkey_not_responding_when_running_a_script/).

Internet connection is 150/50Mbps.

It takes like 2-3 minutes to even start the script. 
Trying to price uniques, prophecies, div cards, maps etc. takes an eternity. 
The machine learning pricing works almost instantly. 
CTRL + Q works fine for now. Poe.trade opens instantly.

I made a small unlisted video that shows the problem (www.youtube.com/watch?v=l64uZmm1vDE).

**Comment by Sapporun** [comment] 2018-06-08 10:40
I got the same issue and my connection is fine.
The launch of poe-trademacro is incredibly slow and the ctrl d searches takes ~2 minutes

**Comment by Eruyome** [comment] 2018-06-08 11:14
https://github.com/PoE-TradeMacro/POE-TradeMacro/tree/dev

Test this version, it shouldn't solve any issue but it writes a file `temp\timings.txt` which logs all requests with url and some times/durations.

**Comment by Sapporun** [comment] 2018-06-08 11:42
only poe.trade seem to be slow according to the timings.txt

> http://poe.trade
Downloading process duration: 60469ms 
Data request duration	  : 187ms 
Header request duration	  : 157ms 
Validating result duration  : 0ms

the rest looks like this
> http://poe.ninja/api/Data/GetCurrencyOverview?league=tmpstandard
Downloading process duration: 312ms 
Data request duration	  : 156ms 
Header request duration	  : 156ms 
Validating result duration  : 0ms

**Comment by Zeronthe** [comment] 2018-06-08 11:44
Here are my startuplog and timings.txt. script initialization took a long time, same with a ctrl d search. ctrl q seemed to work fine with this version.
[timings.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2084197/timings.txt)
[StartupLog.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2084198/StartupLog.txt)

**Comment by ScubaSt3v3** [comment] 2018-06-08 12:31
Tested again this morning at a different location (work) and everything seems to be working correctly again. I will update my timings at home later today, but maybe its fixed now?

I did however install AHK for the first time on this machine, along with the /dev version you provided so that may have something to do with my timings.

> http://poe.ninja/api/Data/GetCurrencyOverview?league=eventhardcore
> Downloading process duration: 297ms 
> Data request duration	  : 78ms 
> Header request duration	  : 78ms 
> Validating result duration  : 31ms 

> http://poe.trade/search
> Downloading process duration: 1109ms 
> Data request duration	  : 625ms 
> Header request duration	  : 484ms 
> Validating result duration  : 0ms 

[StartupLog.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2084338/StartupLog.txt)
[timings.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2084340/timings.txt)

**Comment by Eruyome** [comment] 2018-06-08 12:36
Download the same dev version again, this time show me `temp\timingsDetail.txt`.

Appearently the actual request (curl request + reading result into variable) is pretty fast for all of you while the entire download process takes 60s. 

So I randomly added timestamps to the logfile, hopefully to see where the delay occurs.

**Comment by Sapporun** [comment] 2018-06-08 12:56
[timingsDetail.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2084412/timingsDetail.txt)

**Comment by Eruyome** [comment] 2018-06-08 13:21
That's odd...

```
			t4_1 := A_TickCount
			dataStart := A_TickCount			
			html	:= StdOutStream(curl """" url """" commandData)
			dataEnd := A_TickCount			
			t5_1 := A_TickCount
```

t4_1 is triggered after less than 1ms from function start.
The request downloading the data comes after that and takes 187ms (Data request duration).
t5_1 is triggered after 30 seconds from function start.

Anyway, please repeat (download and run).

**Comment by Eruyome** [comment] 2018-06-08 13:42
I can see from your logfiles that the poe.trade request gets repeated an additional time. The first time it fails (as in the response validates to "invalid"), this whole process takes 60s, the second request succeeds in a few ms.
Every request actually makes 2 request, one for the data and one for the request headers to check the http response code and such. Every request has a 30s timeout, which explains the logged timestamps, there are two 30s jumps.

The curl command from your StartUpLog file suggests the following:
Normally there should be a bunch of headers, including the `HOST` header. This host header is known to cause the request to fail which leads to a second request without this header, which succeeds. This is an issue that only a few people seem to have and so far I don't know how to fix that. 

I could try and completely remove the host header from all requests, at least for all reqeust to trade sites like poe.trade which are being used frequently. I don't know if removing this header will cause issues for other uses though. It may work for all of them which would greatly help people like you.

The real question is why curl failes for some users when using this request and how to fix it:

```
curl.exe "http://poe.trade" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "Accept-Encoding:gzip, deflate" -H "Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "Connection:keep-alive" -H "Host:poe.trade" -H "Upgrade-Insecure-Requests:1" --max-time 30 
```

**Comment by Sapporun** [comment] 2018-06-08 13:48
[timingsDetail.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2084595/timingsDetail.txt)

**Comment by Eruyome** [comment] 2018-06-08 13:53
Try again, I directly removed said host headers from the request.

**Comment by Sapporun** [comment] 2018-06-08 13:56
It started very fast and is working fine now, will update with files

**Comment by Eruyome** [comment] 2018-06-08 14:08
Do me a favour and execute this in a windows console/terminal:

```
"C:\Users\Tandfen\Desktop\POE-TradeMacro-dev\POE-TradeMacro-dev\lib\curl.exe" "http://poe.trade" -ILks -H "User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "Accept-Encoding:gzip, deflate" -H "Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "Connection:keep-alive" -H "Host:poe.trade" -H "Upgrade-Insecure-Requests:1"
```

and show me the result.

**Comment by siisjuu** [comment] 2018-06-08 14:12
This version actually worked fine for me. The script ran fast and I was able to price check items almost instantly.

[timingsDetail.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2084692/timingsDetail.txt)

**Comment by Eruyome** [comment] 2018-06-08 14:19
I now removed all host headers from all requests, it's probably redundant and should still work for everyone. We'll  have to see if it causes any issues.

**Comment by Sapporun** [comment] 2018-06-08 14:23
I tried the execution and got no result at all, the pathing is correct though

**Comment by Zeronthe** [comment] 2018-06-08 14:31
Looks like this new version is working for me as well. Odd that it would just magically stop working for some users at a specific time, but at least this fixes it.

**Comment by Eruyome** [comment] 2018-06-08 14:39
As I expected, thx.

**Comment by machogriz** [comment] 2018-06-08 14:41
Just wanted to chime in. I was having the same issue. I just downloaded and used the dev version and it fixed it for me as well. Thanks for this!

**Comment by joprut** [comment] 2018-06-08 17:05
Seems to be working fine for me too! Thank you for the help. I was sleeping, that's why I wasn't there to help.

**Comment by Eruyome** [comment] 2018-06-08 17:56
Will make a release soon. Anyway, initialization is still somewhat slow because GGGs API is too slow.

**Comment by ScubaSt3v3** [comment] 2018-06-08 18:47
👍 Thanks Eruyome!! You never know how much you use this application until it stops working. I wonder how anyone functions without it :)

**Comment by Eruyome** [comment] 2018-06-09 12:17
This dev version is already released as a new stable version.

**Closed** 2018-06-19 15:38 UTC
