### ISSUE TITLE
Ctrl + c on currency only show Hardcoded prices

### ISSUE THREAD

**Issue by SpeedZealot** [PoE-TradeMacro/POE-TradeMacro#560] opened 2017-10-18 09:47 UTC
![capture](https://user-images.githubusercontent.com/32897737/31711905-e4802aa2-b3f9-11e7-8125-cba3101a6efe.PNG)

Well, everything is in the title and this screenshot.

AHK version: 2.6.0-beta.1

**Comment by SpeedZealot** [comment] 2017-10-18 09:57
It seems that there is a problem with League system because switching league via Ctrl + L  is also not working

**Comment by Eruyome** [comment] 2017-10-18 12:37
Fixed on the TradeMacro beta branch, I'll keep this open for visibility.

**Comment by bferrantino** [comment] 2017-10-19 01:44
@Eruyome i tested the beta, and it appears that the math is incorrect.

Example: 
![image](https://user-images.githubusercontent.com/444114/31750350-79246378-b44d-11e7-9a97-f5e0c6100349.png)

15 Silver coins @ 6.67:1c should not be 100.05 (that is 1:6.67c), seems math is backwards

**Comment by Eruyome** [comment] 2017-10-19 06:03
Hehe, sry, I guess I messed that up while rewriting some code.

**Comment by Eruyome** [comment] 2017-10-19 07:43
Should work now as intended.

**Closed** 2017-10-19 17:48 UTC
