### ISSUE TITLE
Search results window not displaying properly with GDI enabled

### ISSUE THREAD

**Issue by damoochie** [PoE-TradeMacro/POE-TradeMacro#559] opened 2017-10-18 09:00 UTC
![tmfail](https://user-images.githubusercontent.com/13886692/31709777-5d41a6d2-b436-11e7-98f3-e0d0a0fd8f22.jpg)

Like the title says, when I enable the GDI and try to bring up search results within PoE itself, the window simply displays a header with "requesting search results" and a glitchy coloured area with no results. Also, this window does not close until another search box is made to replace the broken one.

Turning the GDI off returns it to working normally.
 
AHK version: 1.1.26.01
Windows version: 10

**Comment by Eruyome** [comment] 2017-10-18 10:27
Wow, that's weird. I probably have to add a lot of debug output to the GDI function and let you try that.

**Comment by damoochie** [comment] 2017-10-18 12:32
All the other windows that pop up when using ctrl + c look good. Border colours also seemed to be changing according to the item type correctly too. Only the window that shows search results from trade seems to be affected.

Let me know if I can provide more info and I'll help if I can. Thanks for replying.

**Comment by Eruyome** [comment] 2017-10-18 12:36
Sure, I have to do that at a later time though.

**Comment by damoochie** [comment] 2017-10-18 14:58
Just noticed it looks ok when I use it to price gems...

**Comment by Eruyome** [comment] 2017-10-18 15:19
Is that consistent? Other items are broken, but gems are ok?

**Comment by damoochie** [comment] 2017-10-18 18:16
I've tested all the different item types I can think of (currency, cards, flasks etc.) and the only one that works is gems.

**Comment by dein0s** [comment] 2017-10-18 18:32
Is that happens only with a game client in forefront?
Can you test `Preview` of tooltip while no game client running at all?

**Comment by damoochie** [comment] 2017-10-18 19:23
Previewing works fine with the game running or not....

**Comment by LillieSatou** [comment] 2017-10-19 22:28
This now does not work at all with 2.6.0.2 beta (doesn't even show up!)

windowed fullscreen, path of exile, dx11 non-steam client.

**Comment by aRTy42** [comment] 2017-10-19 22:43
If the GDI setting was disabled and you enabled it, you need a script restart now to have it take effect.

**Comment by LillieSatou** [comment] 2017-10-20 03:55
It disables upon a script restart OR saving the darn settings.

**Comment by Eruyome** [comment] 2017-10-20 06:55
It does work, at least for me but there seems to be an issue with saving the settings being extremely slow, maybe onla or because the GDI tooltip was initialised (causing lag etc). If you restart the script to soon the ini file in the user folder may end up broken (deleting it may not be a bad idea).

So, having a clean ini file, starting the script, enabling GDI and waiting a while before restarting shoulr work, anyway I'm gonna work on a fix soon.

**Comment by Eruyome** [comment] 2017-10-20 08:06
The initialisation issue should be fixed on the dev branch now, haven't had much time to test it, the saving issue (too slow) still remains for now.
https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/beta.zip

**Comment by damoochie** [comment] 2017-10-21 10:31
Just checking in... I used the above link to test the GDI and it seems to have gotten worse. Same issue as i initially reported but It doesn't even work for gems anymore. And the latest version released also didn't work at all like someone else mentioned.

**Comment by Eruyome** [comment] 2017-10-22 07:28
I'm not aware of any changes that could have cuased the tooltip to not work at all (meaning those graphical "glitches") for you anymore, not even gems. But it was beyond me why gems worked. 
Going back to the version where gems worked, did you have the "Style according to item" option enabled? I know it doesn't change the search border color but could have some influence anyway.

**Comment by damoochie** [comment] 2017-10-23 10:51
I tried all the combinations of enabled/disabled GDI options and nothing worked. I did however lower the amount of results displayed and the font size and it started working for everything again. Seems like the whole box craps out if the text is too big for the box.

**Comment by Eruyome** [comment] 2017-10-23 11:42
At which font size does it start to break?

**Comment by damoochie** [comment] 2017-10-24 11:42
With "show items" at 20, the largest font working is 12 and breaks at 13. It seems to me there's an issue with the box being rendered if the contents are too big.

I can work around this and make it work until you possibly make a full fix.
Cheers

**Comment by Eruyome** [comment] 2017-10-24 14:22
Thanks, I can reproduce it now, may take a few days until I can try to resolve this though.

**Comment by fragfaq** [comment] 2018-01-26 23:36
I ran into a similar problem regarding the font size in GDI+. I was looking for the cause of the problem using different objects and I'll try to describe as simply as possible, my English is very bad and I'm writing this with Google translit, so please forgive me for bad text in advance. The more information about the subject, the less you need to set the font size, if i use GDI+. Otherwise, the information is not displayed. No window, no border, nothing. I noticed this for the first time on maps with a lot of mods. At first I did not attach much importance to this, I made the font smaller and it all worked. I almost forgot about it until I got the Doryani's Invitation from Atziri. When i press ctrl+c, the information window does not appear again. Then I decided to check what font size is needed, what would it work. It turned out that for this item i need font size of 8 or less, although for maps I lacked 10, sometimes 9 (depending on the number of mods and the map). It is worth noting that on simple maps without mods and the font size 19 works correctly. It seemed strange to me, because I still have enough room on the screen for the information window, maybe GDI has some limitation for displaying vertically, I'm not sure. If GDI+ off, everything is displayed correctly, even if I set a large font size. Now I do not use it, but I would really like this functionality, hope it will work correctly in future. 
Thank you for your work, I and my friends are very grateful to you for it

* AHK version: 1.1.27.03 - January 6, 2018
* Windows version: Win7 x64, SP1

**Comment by Eruyome** [comment] 2018-02-28 11:07
I still don't know how to solve this. I started working on a different tooltip solution, maybe that leads to something better.

**Closed** 2019-12-08 19:14 UTC
